// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  workspaceId: __t.string(),
  codingWorkspaceId: __t.string(),
  roomId: __t.string(),
  conversationId: __t.string(),
  streamId: __t.string(),
  receiptId: __t.string(),
  occurredAtMs: __t.u64(),
  prevHash: __t.string(),
  hash: __t.string(),
  bodyJson: __t.string(),
  hintsJson: __t.string(),
};
