// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  workspaceId: __t.string(),
  nodeId: __t.string(),
  deliveryId: __t.string(),
  cause: __t.string(),
  laneId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  sourceId: __t.string(),
  sourceVersion: __t.string(),
  sourceHash: __t.string(),
  payloadReference: __t.string(),
  causalParentId: __t.string(),
  causalDepth: __t.u32(),
  deliveredAtMs: __t.u64(),
  requestWake: __t.bool(),
  wakeRequestId: __t.string(),
  notBeforeMs: __t.u64(),
};
