// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  workspaceId: __t.string(),
  requestId: __t.string(),
  jobId: __t.string(),
  agentId: __t.string(),
  lane: __t.string(),
  sessionKey: __t.string(),
  singletonMode: __t.string(),
  payloadJson: __t.string(),
  maxAttempts: __t.u32(),
};
