// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.1 (commit 052c83fe984a4c4eb7bb4f9afa5c6b1903891d87).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptRosterTaskOutcomeReducer from "./accept_roster_task_outcome_reducer.js";
import AddRunMemberReducer from "./add_run_member_reducer.js";
import AddWorkspaceMemberReducer from "./add_workspace_member_reducer.js";
import AdmitRosterNodeWakeReducer from "./admit_roster_node_wake_reducer.js";
import AppendCodingRoomReceiptReducer from "./append_coding_room_receipt_reducer.js";
import AppendRosterRoomTimelineEntryReducer from "./append_roster_room_timeline_entry_reducer.js";
import AppendStreamReceiptReducer from "./append_stream_receipt_reducer.js";
import BindRosterNodeRuntimeReducer from "./bind_roster_node_runtime_reducer.js";
import CancelCanvasRunReducer from "./cancel_canvas_run_reducer.js";
import CancelRosterExecutionReducer from "./cancel_roster_execution_reducer.js";
import CancelRosterJobReducer from "./cancel_roster_job_reducer.js";
import CancelRosterTaskReducer from "./cancel_roster_task_reducer.js";
import ChangeRosterNodeCommitmentReducer from "./change_roster_node_commitment_reducer.js";
import CheckpointRosterSharedWorkspaceReducer from "./checkpoint_roster_shared_workspace_reducer.js";
import ClaimNextRosterJobReducer from "./claim_next_roster_job_reducer.js";
import ClaimRosterTaskReducer from "./claim_roster_task_reducer.js";
import CompleteRosterJobReducer from "./complete_roster_job_reducer.js";
import CompleteRosterNodeWakeReducer from "./complete_roster_node_wake_reducer.js";
import ConsumeRosterJobCommandsReducer from "./consume_roster_job_commands_reducer.js";
import ConsumeRosterRoomControlIntentReducer from "./consume_roster_room_control_intent_reducer.js";
import CreateCanvasRunReducer from "./create_canvas_run_reducer.js";
import CreateViewerCapabilityReducer from "./create_viewer_capability_reducer.js";
import CreateWorkspaceViewerCapabilityReducer from "./create_workspace_viewer_capability_reducer.js";
import DeliverRosterNodeInboxReducer from "./deliver_roster_node_inbox_reducer.js";
import EnqueueRosterJobReducer from "./enqueue_roster_job_reducer.js";
import EnqueueRosterTaskReducer from "./enqueue_roster_task_reducer.js";
import EnsureEventStreamReducer from "./ensure_event_stream_reducer.js";
import EnsureRosterExecutionReducer from "./ensure_roster_execution_reducer.js";
import EnsureWorkspaceReducer from "./ensure_workspace_reducer.js";
import ExpandAndDelegateRosterTaskReducer from "./expand_and_delegate_roster_task_reducer.js";
import FailRosterJobReducer from "./fail_roster_job_reducer.js";
import FailRosterNodeWakeReducer from "./fail_roster_node_wake_reducer.js";
import FailRosterTaskReducer from "./fail_roster_task_reducer.js";
import FinalizeCanvasRunReducer from "./finalize_canvas_run_reducer.js";
import FinalizeRosterExecutionReducer from "./finalize_roster_execution_reducer.js";
import HeartbeatRosterJobReducer from "./heartbeat_roster_job_reducer.js";
import HeartbeatRosterTaskReducer from "./heartbeat_roster_task_reducer.js";
import InitializeRosterExecutionReducer from "./initialize_roster_execution_reducer.js";
import JoinCanvasRunReducer from "./join_canvas_run_reducer.js";
import JoinCanvasWorkspaceRunReducer from "./join_canvas_workspace_run_reducer.js";
import JoinWorkspaceReducer from "./join_workspace_reducer.js";
import LinkCanvasRunWorkspaceReducer from "./link_canvas_run_workspace_reducer.js";
import MarkRosterModelReservationDispatchedReducer from "./mark_roster_model_reservation_dispatched_reducer.js";
import ProjectCanvasEventReducer from "./project_canvas_event_reducer.js";
import PublishRosterSharedWorkspaceUpdateReducer from "./publish_roster_shared_workspace_update_reducer.js";
import QueueRosterJobCommandReducer from "./queue_roster_job_command_reducer.js";
import QueueRosterRoomControlIntentReducer from "./queue_roster_room_control_intent_reducer.js";
import ReconcileTerminalRosterJobCommandsReducer from "./reconcile_terminal_roster_job_commands_reducer.js";
import RegisterRosterWorkspaceNodeReducer from "./register_roster_workspace_node_reducer.js";
import RequestRosterNodeWakeReducer from "./request_roster_node_wake_reducer.js";
import ReserveRosterModelCallReducer from "./reserve_roster_model_call_reducer.js";
import ResolveFailedRosterNodeWakeReducer from "./resolve_failed_roster_node_wake_reducer.js";
import ResumeRosterNodeContinuityReducer from "./resume_roster_node_continuity_reducer.js";
import RevokeViewerCapabilityReducer from "./revoke_viewer_capability_reducer.js";
import RevokeWorkspaceViewerCapabilityReducer from "./revoke_workspace_viewer_capability_reducer.js";
import SaveRosterParticipantProfileReducer from "./save_roster_participant_profile_reducer.js";
import SelectCodingRoomTimelinePageReducer from "./select_coding_room_timeline_page_reducer.js";
import SetRosterWorkerCapabilitiesReducer from "./set_roster_worker_capabilities_reducer.js";
import SettleRosterModelReservationReducer from "./settle_roster_model_reservation_reducer.js";
import StartRosterTaskReducer from "./start_roster_task_reducer.js";
import SuspendRosterNodeContinuityReducer from "./suspend_roster_node_continuity_reducer.js";
import UpdateRosterNodeMemoryFrontierReducer from "./update_roster_node_memory_frontier_reducer.js";

// Import all procedure arg schemas

// Import all table schema definitions
import MyCanvasActivityRow from "./my_canvas_activity_table.js";
import MyCanvasAgentsRow from "./my_canvas_agents_table.js";
import MyCanvasFleetRunsRow from "./my_canvas_fleet_runs_table.js";
import MyCanvasReplayStepsRow from "./my_canvas_replay_steps_table.js";
import MyCanvasRunUiRow from "./my_canvas_run_ui_table.js";
import MyCanvasRunsRow from "./my_canvas_runs_table.js";
import MyCanvasTaskStatusesRow from "./my_canvas_task_statuses_table.js";
import MyClaimableRosterTasksRow from "./my_claimable_roster_tasks_table.js";
import MyCodingActiveRuntimeBindingsWindowRow from "./my_coding_active_runtime_bindings_window_table.js";
import MyCodingCollaborationSummariesWindowRow from "./my_coding_collaboration_summaries_window_table.js";
import MyCodingContextFrontiersWindowRow from "./my_coding_context_frontiers_window_table.js";
import MyCodingControlIntentDeliveriesWindowRow from "./my_coding_control_intent_deliveries_window_table.js";
import MyCodingExecutionSummariesWindowRow from "./my_coding_execution_summaries_window_table.js";
import MyCodingParticipantProfilesWindowRow from "./my_coding_participant_profiles_window_table.js";
import MyCodingRoomNodesWindowRow from "./my_coding_room_nodes_window_table.js";
import MyCodingRoomTimelineRow from "./my_coding_room_timeline_table.js";
import MyCodingRoomTimelinePageRow from "./my_coding_room_timeline_page_table.js";
import MyCodingRoomTimelineWindowRow from "./my_coding_room_timeline_window_table.js";
import MyCodingRoomsRow from "./my_coding_rooms_table.js";
import MyCodingRoomsWindowRow from "./my_coding_rooms_window_table.js";
import MyCodingRunTaskEdgesWindowRow from "./my_coding_run_task_edges_window_table.js";
import MyCodingRunTaskOutputReferencesWindowRow from "./my_coding_run_task_output_references_window_table.js";
import MyCodingRunTasksWindowRow from "./my_coding_run_tasks_window_table.js";
import MyEventStreamsRow from "./my_event_streams_table.js";
import MyReceiptsRow from "./my_receipts_table.js";
import MyRosterCollaborationSummariesRow from "./my_roster_collaboration_summaries_table.js";
import MyRosterContextFrontiersRow from "./my_roster_context_frontiers_table.js";
import MyRosterControlIntentDeliveriesRow from "./my_roster_control_intent_deliveries_table.js";
import MyRosterControlIntentsRow from "./my_roster_control_intents_table.js";
import MyRosterExecutionSummariesRow from "./my_roster_execution_summaries_table.js";
import MyRosterJobCommandsRow from "./my_roster_job_commands_table.js";
import MyRosterJobEventsRow from "./my_roster_job_events_table.js";
import MyRosterJobRequestsRow from "./my_roster_job_requests_table.js";
import MyRosterJobsRow from "./my_roster_jobs_table.js";
import MyRosterModelReservationsRow from "./my_roster_model_reservations_table.js";
import MyRosterNodeCommitmentsRow from "./my_roster_node_commitments_table.js";
import MyRosterNodeContinuitiesRow from "./my_roster_node_continuities_table.js";
import MyRosterNodeContinuityEventsRow from "./my_roster_node_continuity_events_table.js";
import MyRosterNodeInboxItemsRow from "./my_roster_node_inbox_items_table.js";
import MyRosterNodeWakesRow from "./my_roster_node_wakes_table.js";
import MyRosterParticipantProfilesRow from "./my_roster_participant_profiles_table.js";
import MyRosterProjectionOutboxRow from "./my_roster_projection_outbox_table.js";
import MyRosterRoomNodesRow from "./my_roster_room_nodes_table.js";
import MyRosterRoomTimelineEntriesRow from "./my_roster_room_timeline_entries_table.js";
import MyRosterRoomsRow from "./my_roster_rooms_table.js";
import MyRosterRuntimeBindingsRow from "./my_roster_runtime_bindings_table.js";
import MyRosterSharedWorkspaceCheckpointsRow from "./my_roster_shared_workspace_checkpoints_table.js";
import MyRosterSharedWorkspaceUpdatesRow from "./my_roster_shared_workspace_updates_table.js";
import MyRosterTaskContextManifestsRow from "./my_roster_task_context_manifests_table.js";
import MyRosterTaskEdgesRow from "./my_roster_task_edges_table.js";
import MyRosterTaskExpansionsRow from "./my_roster_task_expansions_table.js";
import MyRosterTaskOutcomesRow from "./my_roster_task_outcomes_table.js";
import MyRosterTaskOutputReferencesRow from "./my_roster_task_output_references_table.js";
import MyRosterTasksRow from "./my_roster_tasks_table.js";
import MyRosterWorkerCapabilitiesRow from "./my_roster_worker_capabilities_table.js";
import MyRosterWorkspaceNodesRow from "./my_roster_workspace_nodes_table.js";
import MyRunMembersRow from "./my_run_members_table.js";
import MySceneObjectsRow from "./my_scene_objects_table.js";
import MyScenePatchesRow from "./my_scene_patches_table.js";
import MyScenePlanRow from "./my_scene_plan_table.js";
import MyScenePlanPartsRow from "./my_scene_plan_parts_table.js";
import MySceneReviewsRow from "./my_scene_reviews_table.js";
import MyStreamBranchesRow from "./my_stream_branches_table.js";
import MyStreamReceiptsRow from "./my_stream_receipts_table.js";
import MyWorkspaceUsageRow from "./my_workspace_usage_table.js";
import MyWorkspacesRow from "./my_workspaces_table.js";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  myCanvasActivity: __table({
    name: 'my_canvas_activity',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCanvasActivityRow),
  myCanvasAgents: __table({
    name: 'my_canvas_agents',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCanvasAgentsRow),
  myCanvasFleetRuns: __table({
    name: 'my_canvas_fleet_runs',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCanvasFleetRunsRow),
  myCanvasReplaySteps: __table({
    name: 'my_canvas_replay_steps',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCanvasReplayStepsRow),
  myCanvasRunUi: __table({
    name: 'my_canvas_run_ui',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCanvasRunUiRow),
  myCanvasRuns: __table({
    name: 'my_canvas_runs',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCanvasRunsRow),
  myCanvasTaskStatuses: __table({
    name: 'my_canvas_task_statuses',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCanvasTaskStatusesRow),
  myClaimableRosterTasks: __table({
    name: 'my_claimable_roster_tasks',
    indexes: [
    ],
    constraints: [
    ],
  }, MyClaimableRosterTasksRow),
  myCodingActiveRuntimeBindingsWindow: __table({
    name: 'my_coding_active_runtime_bindings_window',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingActiveRuntimeBindingsWindowRow),
  myCodingCollaborationSummariesWindow: __table({
    name: 'my_coding_collaboration_summaries_window',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingCollaborationSummariesWindowRow),
  myCodingContextFrontiersWindow: __table({
    name: 'my_coding_context_frontiers_window',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingContextFrontiersWindowRow),
  myCodingControlIntentDeliveriesWindow: __table({
    name: 'my_coding_control_intent_deliveries_window',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingControlIntentDeliveriesWindowRow),
  myCodingExecutionSummariesWindow: __table({
    name: 'my_coding_execution_summaries_window',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingExecutionSummariesWindowRow),
  myCodingParticipantProfilesWindow: __table({
    name: 'my_coding_participant_profiles_window',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingParticipantProfilesWindowRow),
  myCodingRoomNodesWindow: __table({
    name: 'my_coding_room_nodes_window',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingRoomNodesWindowRow),
  myCodingRoomTimeline: __table({
    name: 'my_coding_room_timeline',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingRoomTimelineRow),
  myCodingRoomTimelinePage: __table({
    name: 'my_coding_room_timeline_page',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingRoomTimelinePageRow),
  myCodingRoomTimelineWindow: __table({
    name: 'my_coding_room_timeline_window',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingRoomTimelineWindowRow),
  myCodingRooms: __table({
    name: 'my_coding_rooms',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingRoomsRow),
  myCodingRoomsWindow: __table({
    name: 'my_coding_rooms_window',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingRoomsWindowRow),
  myCodingRunTaskEdgesWindow: __table({
    name: 'my_coding_run_task_edges_window',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingRunTaskEdgesWindowRow),
  myCodingRunTaskOutputReferencesWindow: __table({
    name: 'my_coding_run_task_output_references_window',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingRunTaskOutputReferencesWindowRow),
  myCodingRunTasksWindow: __table({
    name: 'my_coding_run_tasks_window',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCodingRunTasksWindowRow),
  myEventStreams: __table({
    name: 'my_event_streams',
    indexes: [
    ],
    constraints: [
    ],
  }, MyEventStreamsRow),
  myReceipts: __table({
    name: 'my_receipts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyReceiptsRow),
  myRosterCollaborationSummaries: __table({
    name: 'my_roster_collaboration_summaries',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterCollaborationSummariesRow),
  myRosterContextFrontiers: __table({
    name: 'my_roster_context_frontiers',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterContextFrontiersRow),
  myRosterControlIntentDeliveries: __table({
    name: 'my_roster_control_intent_deliveries',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterControlIntentDeliveriesRow),
  myRosterControlIntents: __table({
    name: 'my_roster_control_intents',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterControlIntentsRow),
  myRosterExecutionSummaries: __table({
    name: 'my_roster_execution_summaries',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterExecutionSummariesRow),
  myRosterJobCommands: __table({
    name: 'my_roster_job_commands',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterJobCommandsRow),
  myRosterJobEvents: __table({
    name: 'my_roster_job_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterJobEventsRow),
  myRosterJobRequests: __table({
    name: 'my_roster_job_requests',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterJobRequestsRow),
  myRosterJobs: __table({
    name: 'my_roster_jobs',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterJobsRow),
  myRosterModelReservations: __table({
    name: 'my_roster_model_reservations',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterModelReservationsRow),
  myRosterNodeCommitments: __table({
    name: 'my_roster_node_commitments',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterNodeCommitmentsRow),
  myRosterNodeContinuities: __table({
    name: 'my_roster_node_continuities',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterNodeContinuitiesRow),
  myRosterNodeContinuityEvents: __table({
    name: 'my_roster_node_continuity_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterNodeContinuityEventsRow),
  myRosterNodeInboxItems: __table({
    name: 'my_roster_node_inbox_items',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterNodeInboxItemsRow),
  myRosterNodeWakes: __table({
    name: 'my_roster_node_wakes',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterNodeWakesRow),
  myRosterParticipantProfiles: __table({
    name: 'my_roster_participant_profiles',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterParticipantProfilesRow),
  myRosterProjectionOutbox: __table({
    name: 'my_roster_projection_outbox',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterProjectionOutboxRow),
  myRosterRoomNodes: __table({
    name: 'my_roster_room_nodes',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterRoomNodesRow),
  myRosterRoomTimelineEntries: __table({
    name: 'my_roster_room_timeline_entries',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterRoomTimelineEntriesRow),
  myRosterRooms: __table({
    name: 'my_roster_rooms',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterRoomsRow),
  myRosterRuntimeBindings: __table({
    name: 'my_roster_runtime_bindings',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterRuntimeBindingsRow),
  myRosterSharedWorkspaceCheckpoints: __table({
    name: 'my_roster_shared_workspace_checkpoints',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterSharedWorkspaceCheckpointsRow),
  myRosterSharedWorkspaceUpdates: __table({
    name: 'my_roster_shared_workspace_updates',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterSharedWorkspaceUpdatesRow),
  myRosterTaskContextManifests: __table({
    name: 'my_roster_task_context_manifests',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterTaskContextManifestsRow),
  myRosterTaskEdges: __table({
    name: 'my_roster_task_edges',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterTaskEdgesRow),
  myRosterTaskExpansions: __table({
    name: 'my_roster_task_expansions',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterTaskExpansionsRow),
  myRosterTaskOutcomes: __table({
    name: 'my_roster_task_outcomes',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterTaskOutcomesRow),
  myRosterTaskOutputReferences: __table({
    name: 'my_roster_task_output_references',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterTaskOutputReferencesRow),
  myRosterTasks: __table({
    name: 'my_roster_tasks',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterTasksRow),
  myRosterWorkerCapabilities: __table({
    name: 'my_roster_worker_capabilities',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterWorkerCapabilitiesRow),
  myRosterWorkspaceNodes: __table({
    name: 'my_roster_workspace_nodes',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRosterWorkspaceNodesRow),
  myRunMembers: __table({
    name: 'my_run_members',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRunMembersRow),
  mySceneObjects: __table({
    name: 'my_scene_objects',
    indexes: [
    ],
    constraints: [
    ],
  }, MySceneObjectsRow),
  myScenePatches: __table({
    name: 'my_scene_patches',
    indexes: [
    ],
    constraints: [
    ],
  }, MyScenePatchesRow),
  myScenePlan: __table({
    name: 'my_scene_plan',
    indexes: [
    ],
    constraints: [
    ],
  }, MyScenePlanRow),
  myScenePlanParts: __table({
    name: 'my_scene_plan_parts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyScenePlanPartsRow),
  mySceneReviews: __table({
    name: 'my_scene_reviews',
    indexes: [
    ],
    constraints: [
    ],
  }, MySceneReviewsRow),
  myStreamBranches: __table({
    name: 'my_stream_branches',
    indexes: [
    ],
    constraints: [
    ],
  }, MyStreamBranchesRow),
  myStreamReceipts: __table({
    name: 'my_stream_receipts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyStreamReceiptsRow),
  myWorkspaceUsage: __table({
    name: 'my_workspace_usage',
    indexes: [
    ],
    constraints: [
    ],
  }, MyWorkspaceUsageRow),
  myWorkspaces: __table({
    name: 'my_workspaces',
    indexes: [
    ],
    constraints: [
    ],
  }, MyWorkspacesRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_roster_task_outcome", AcceptRosterTaskOutcomeReducer),
  __reducerSchema("add_run_member", AddRunMemberReducer),
  __reducerSchema("add_workspace_member", AddWorkspaceMemberReducer),
  __reducerSchema("admit_roster_node_wake", AdmitRosterNodeWakeReducer),
  __reducerSchema("append_coding_room_receipt", AppendCodingRoomReceiptReducer),
  __reducerSchema("append_roster_room_timeline_entry", AppendRosterRoomTimelineEntryReducer),
  __reducerSchema("append_stream_receipt", AppendStreamReceiptReducer),
  __reducerSchema("bind_roster_node_runtime", BindRosterNodeRuntimeReducer),
  __reducerSchema("cancel_canvas_run", CancelCanvasRunReducer),
  __reducerSchema("cancel_roster_execution", CancelRosterExecutionReducer),
  __reducerSchema("cancel_roster_job", CancelRosterJobReducer),
  __reducerSchema("cancel_roster_task", CancelRosterTaskReducer),
  __reducerSchema("change_roster_node_commitment", ChangeRosterNodeCommitmentReducer),
  __reducerSchema("checkpoint_roster_shared_workspace", CheckpointRosterSharedWorkspaceReducer),
  __reducerSchema("claim_next_roster_job", ClaimNextRosterJobReducer),
  __reducerSchema("claim_roster_task", ClaimRosterTaskReducer),
  __reducerSchema("complete_roster_job", CompleteRosterJobReducer),
  __reducerSchema("complete_roster_node_wake", CompleteRosterNodeWakeReducer),
  __reducerSchema("consume_roster_job_commands", ConsumeRosterJobCommandsReducer),
  __reducerSchema("consume_roster_room_control_intent", ConsumeRosterRoomControlIntentReducer),
  __reducerSchema("create_canvas_run", CreateCanvasRunReducer),
  __reducerSchema("create_viewer_capability", CreateViewerCapabilityReducer),
  __reducerSchema("create_workspace_viewer_capability", CreateWorkspaceViewerCapabilityReducer),
  __reducerSchema("deliver_roster_node_inbox", DeliverRosterNodeInboxReducer),
  __reducerSchema("enqueue_roster_job", EnqueueRosterJobReducer),
  __reducerSchema("enqueue_roster_task", EnqueueRosterTaskReducer),
  __reducerSchema("ensure_event_stream", EnsureEventStreamReducer),
  __reducerSchema("ensure_roster_execution", EnsureRosterExecutionReducer),
  __reducerSchema("ensure_workspace", EnsureWorkspaceReducer),
  __reducerSchema("expand_and_delegate_roster_task", ExpandAndDelegateRosterTaskReducer),
  __reducerSchema("fail_roster_job", FailRosterJobReducer),
  __reducerSchema("fail_roster_node_wake", FailRosterNodeWakeReducer),
  __reducerSchema("fail_roster_task", FailRosterTaskReducer),
  __reducerSchema("finalize_canvas_run", FinalizeCanvasRunReducer),
  __reducerSchema("finalize_roster_execution", FinalizeRosterExecutionReducer),
  __reducerSchema("heartbeat_roster_job", HeartbeatRosterJobReducer),
  __reducerSchema("heartbeat_roster_task", HeartbeatRosterTaskReducer),
  __reducerSchema("initialize_roster_execution", InitializeRosterExecutionReducer),
  __reducerSchema("join_canvas_run", JoinCanvasRunReducer),
  __reducerSchema("join_canvas_workspace_run", JoinCanvasWorkspaceRunReducer),
  __reducerSchema("join_workspace", JoinWorkspaceReducer),
  __reducerSchema("link_canvas_run_workspace", LinkCanvasRunWorkspaceReducer),
  __reducerSchema("mark_roster_model_reservation_dispatched", MarkRosterModelReservationDispatchedReducer),
  __reducerSchema("project_canvas_event", ProjectCanvasEventReducer),
  __reducerSchema("publish_roster_shared_workspace_update", PublishRosterSharedWorkspaceUpdateReducer),
  __reducerSchema("queue_roster_job_command", QueueRosterJobCommandReducer),
  __reducerSchema("queue_roster_room_control_intent", QueueRosterRoomControlIntentReducer),
  __reducerSchema("reconcile_terminal_roster_job_commands", ReconcileTerminalRosterJobCommandsReducer),
  __reducerSchema("register_roster_workspace_node", RegisterRosterWorkspaceNodeReducer),
  __reducerSchema("request_roster_node_wake", RequestRosterNodeWakeReducer),
  __reducerSchema("reserve_roster_model_call", ReserveRosterModelCallReducer),
  __reducerSchema("resolve_failed_roster_node_wake", ResolveFailedRosterNodeWakeReducer),
  __reducerSchema("resume_roster_node_continuity", ResumeRosterNodeContinuityReducer),
  __reducerSchema("revoke_viewer_capability", RevokeViewerCapabilityReducer),
  __reducerSchema("revoke_workspace_viewer_capability", RevokeWorkspaceViewerCapabilityReducer),
  __reducerSchema("save_roster_participant_profile", SaveRosterParticipantProfileReducer),
  __reducerSchema("select_coding_room_timeline_page", SelectCodingRoomTimelinePageReducer),
  __reducerSchema("set_roster_worker_capabilities", SetRosterWorkerCapabilitiesReducer),
  __reducerSchema("settle_roster_model_reservation", SettleRosterModelReservationReducer),
  __reducerSchema("start_roster_task", StartRosterTaskReducer),
  __reducerSchema("suspend_roster_node_continuity", SuspendRosterNodeContinuityReducer),
  __reducerSchema("update_roster_node_memory_frontier", UpdateRosterNodeMemoryFrontierReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.6.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}
