// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  seq: __t.u64(),
  kind: __t.string(),
  agentId: __t.string().name("agent_id"),
  agentName: __t.string().name("agent_name"),
  summary: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
