// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  runId: __t.string().primaryKey().name("run_id"),
  workspaceId: __t.string().name("workspace_id"),
  kind: __t.string(),
  status: __t.string(),
  graphVersion: __t.u64().name("graph_version"),
  totalTasks: __t.u32().name("total_tasks"),
  readyTasks: __t.u32().name("ready_tasks"),
  blockedTasks: __t.u32().name("blocked_tasks"),
  inflightTasks: __t.u32().name("inflight_tasks"),
  acceptedTasks: __t.u32().name("accepted_tasks"),
  failedTasks: __t.u32().name("failed_tasks"),
  canceledTasks: __t.u32().name("canceled_tasks"),
  skippedTasks: __t.u32().name("skipped_tasks"),
  terminalReason: __t.string().name("terminal_reason"),
  updatedAt: __t.timestamp().name("updated_at"),
});
