// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  agentId: __t.string().name("agent_id"),
  name: __t.string(),
  role: __t.string(),
  group: __t.string(),
  focus: __t.string(),
  assignment: __t.string(),
  model: __t.string(),
  status: __t.string(),
  taskId: __t.string().name("task_id"),
  metadataJson: __t.string().name("metadata_json"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
