// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  taskKey: __t.string().name("task_key"),
  taskId: __t.string().name("task_id"),
  outcomeId: __t.string().name("outcome_id"),
  artifactId: __t.string().name("artifact_id"),
  outputKey: __t.string().name("output_key"),
  createdAt: __t.timestamp().name("created_at"),
});
