// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  codingWorkspaceId: __t.string().name("coding_workspace_id"),
  roomId: __t.string().name("room_id"),
  conversationId: __t.string().name("conversation_id"),
  streamId: __t.string().name("stream_id"),
  title: __t.string(),
  state: __t.string(),
  firstMessageId: __t.string().name("first_message_id"),
  messageCount: __t.u32().name("message_count"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
