// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  owner: __t.identity(),
  prompt: __t.string(),
  status: __t.string(),
  desiredAgents: __t.u32().name("desired_agents"),
  maxInflight: __t.u32().name("max_inflight"),
  nextReceiptSeq: __t.u64().name("next_receipt_seq"),
  headReceiptHash: __t.string().name("head_receipt_hash"),
  budgetMicros: __t.u64().name("budget_micros"),
  reservedMicros: __t.u64().name("reserved_micros"),
  spentMicros: __t.u64().name("spent_micros"),
  sceneHash: __t.string().name("scene_hash"),
  objectCount: __t.u32().name("object_count"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
