// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  prompt: __t.string(),
  status: __t.string(),
  desiredAgents: __t.u32().name("desired_agents"),
  maxInflight: __t.u32().name("max_inflight"),
  objectCount: __t.u32().name("object_count"),
  activeAgents: __t.u32().name("active_agents"),
  totalAgents: __t.u32().name("total_agents"),
  totalTasks: __t.u32().name("total_tasks"),
  completedTasks: __t.u32().name("completed_tasks"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
