// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  runId: __t.string().primaryKey().name("run_id"),
  workspaceId: __t.string().name("workspace_id"),
  proposalCount: __t.u32().name("proposal_count"),
  responseCount: __t.u32().name("response_count"),
  endorsementCount: __t.u32().name("endorsement_count"),
  updatedAt: __t.timestamp().name("updated_at"),
});
