// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  prompt: __t.string(),
  status: __t.string(),
  uiStatus: __t.string().name("ui_status"),
  statusNote: __t.string().name("status_note"),
  desiredAgents: __t.u32().name("desired_agents"),
  maxInflight: __t.u32().name("max_inflight"),
  sceneHash: __t.string().name("scene_hash"),
  objectCount: __t.u32().name("object_count"),
  modelRoutingJson: __t.string().name("model_routing_json"),
  configJson: __t.string().name("config_json"),
  workflowId: __t.string().name("workflow_id"),
  workflowVersion: __t.string().name("workflow_version"),
  planVersion: __t.string().name("plan_version"),
  reviewSceneHash: __t.string().name("review_scene_hash"),
  reviewVerdict: __t.string().name("review_verdict"),
  qualityStatus: __t.string().name("quality_status"),
  totalTasks: __t.u32().name("total_tasks"),
  completedTasks: __t.u32().name("completed_tasks"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
