// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  taskId: __t.string().name("task_id"),
  nodeId: __t.string().name("node_id"),
  capability: __t.string(),
  status: __t.string(),
  attempt: __t.u32(),
  failureCategory: __t.string().name("failure_category"),
  failureReason: __t.string().name("failure_reason"),
  updatedAt: __t.timestamp().name("updated_at"),
});
