// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  seq: __t.u64(),
  kind: __t.string(),
  agentId: __t.string().name("agent_id"),
  label: __t.string(),
  patchId: __t.string().name("patch_id"),
  supersedesPatchId: __t.string().name("supersedes_patch_id"),
  partId: __t.string().name("part_id"),
  status: __t.string(),
  objectCount: __t.u32().name("object_count"),
  createdAt: __t.timestamp().name("created_at"),
});
