// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  taskId: __t.string().name("task_id"),
  delegationId: __t.string().name("delegation_id"),
  agentId: __t.string().name("agent_id"),
  capability: __t.string(),
  objective: __t.string(),
  parentTaskId: __t.string().name("parent_task_id"),
  planId: __t.string().name("plan_id"),
  planVersion: __t.string().name("plan_version"),
  status: __t.string(),
  attempt: __t.u32(),
  needsJson: __t.string().name("needs_json"),
  providesJson: __t.string().name("provides_json"),
  inputVersionsJson: __t.string().name("input_versions_json"),
  artifactIdsJson: __t.string().name("artifact_ids_json"),
  error: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
