// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  parentTaskKey: __t.string().name("parent_task_key"),
  parentTaskId: __t.string().name("parent_task_id"),
  publicationFence: __t.u64().name("publication_fence"),
  expansionKey: __t.string().name("expansion_key"),
  expansionSpecJson: __t.string().name("expansion_spec_json"),
  childCount: __t.u32().name("child_count"),
  continuationTaskId: __t.string().name("continuation_task_id"),
  delegatedBy: __t.identity().name("delegated_by"),
  createdAt: __t.timestamp().name("created_at"),
});
