// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  roomId: __t.string().name("room_id"),
  runId: __t.string().name("run_id"),
  artifactId: __t.string().name("artifact_id"),
  checkpointId: __t.string().name("checkpoint_id"),
  throughUpdateId: __t.string().name("through_update_id"),
  frontierVersion: __t.string().name("frontier_version"),
  topologyVersion: __t.string().name("topology_version"),
  stateBase64: __t.string().name("state_base_64"),
  stateBytes: __t.u32().name("state_bytes"),
  createdAt: __t.timestamp().name("created_at"),
});
