// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  roomId: __t.string().name("room_id"),
  runId: __t.string().name("run_id"),
  taskId: __t.string().name("task_id"),
  nodeId: __t.string().name("node_id"),
  attempt: __t.u32(),
  fence: __t.u64(),
  manifestId: __t.string().name("manifest_id"),
  contextVersion: __t.string().name("context_version"),
  frontierVersion: __t.string().name("frontier_version"),
  topologyVersion: __t.string().name("topology_version"),
  catalogVersion: __t.string().name("catalog_version"),
  bindingVersion: __t.u64().name("binding_version"),
  manifestJson: __t.string().name("manifest_json"),
  createdAt: __t.timestamp().name("created_at"),
});
