// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  agentId: __t.string().name("agent_id"),
  lane: __t.string(),
  sessionKey: __t.string().name("session_key"),
  singletonMode: __t.string().name("singleton_mode"),
  payloadJson: __t.string().name("payload_json"),
  status: __t.string(),
  attempt: __t.u32(),
  maxAttempts: __t.u32().name("max_attempts"),
  leaseOwner: __t.option(__t.identity()).name("lease_owner"),
  leaseWorker: __t.string().name("lease_worker"),
  leaseFence: __t.u64().name("lease_fence"),
  leaseUntil: __t.option(__t.timestamp()).name("lease_until"),
  claimToken: __t.string().name("claim_token"),
  availableAt: __t.timestamp().name("available_at"),
  lastError: __t.string().name("last_error"),
  resultJson: __t.string().name("result_json"),
  canceledReason: __t.string().name("canceled_reason"),
  abortRequested: __t.bool().name("abort_requested"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
