// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  roomId: __t.string().name("room_id"),
  runId: __t.string().name("run_id"),
  seq: __t.u64(),
  kind: __t.string(),
  taskId: __t.string().name("task_id"),
  nodeId: __t.string().name("node_id"),
  entryJson: __t.string().name("entry_json"),
  createdAt: __t.timestamp().name("created_at"),
});
