// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  runId: __t.string().primaryKey().name("run_id"),
  protocolVersion: __t.string().name("protocol_version"),
  kind: __t.string(),
  workspaceId: __t.string().name("workspace_id"),
  receiptStreamId: __t.string().name("receipt_stream_id"),
  status: __t.string(),
  policyJson: __t.string().name("policy_json"),
  graphVersion: __t.u64().name("graph_version"),
  totalTasks: __t.u32().name("total_tasks"),
  readyTasks: __t.u32().name("ready_tasks"),
  blockedTasks: __t.u32().name("blocked_tasks"),
  inflightTasks: __t.u32().name("inflight_tasks"),
  acceptedTasks: __t.u32().name("accepted_tasks"),
  failedTasks: __t.u32().name("failed_tasks"),
  delegatedTasks: __t.u32().name("delegated_tasks"),
  canceledTasks: __t.u32().name("canceled_tasks"),
  skippedTasks: __t.u32().name("skipped_tasks"),
  contextBytes: __t.u64().name("context_bytes"),
  reservedCostMicros: __t.u64().name("reserved_cost_micros"),
  spentCostMicros: __t.u64().name("spent_cost_micros"),
  usedTokens: __t.u64().name("used_tokens"),
  terminalReason: __t.string().name("terminal_reason"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
