// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  outcomeId: __t.string().primaryKey().name("outcome_id"),
  runId: __t.string().name("run_id"),
  taskKey: __t.string().name("task_key"),
  definitionHash: __t.string().name("definition_hash"),
  outcomeJson: __t.string().name("outcome_json"),
  artifactsJson: __t.string().name("artifacts_json"),
  usageJson: __t.string().name("usage_json"),
  actualCostMicros: __t.u64().name("actual_cost_micros"),
  totalTokens: __t.u64().name("total_tokens"),
  createdAt: __t.timestamp().name("created_at"),
});
