// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  nodeId: __t.string().name("node_id"),
  status: __t.string(),
  revision: __t.u64(),
  nextInboxSeq: __t.u64().name("next_inbox_seq"),
  nextEventSeq: __t.u64().name("next_event_seq"),
  pendingInboxCount: __t.u32().name("pending_inbox_count"),
  activeWakeId: __t.string().name("active_wake_id"),
  lastWakeId: __t.string().name("last_wake_id"),
  lastWakeAtMs: __t.u64().name("last_wake_at_ms"),
  wakeWindowStartedAtMs: __t.u64().name("wake_window_started_at_ms"),
  wakesInWindow: __t.u32().name("wakes_in_window"),
  memoryScopeId: __t.string().name("memory_scope_id"),
  memorySnapshotVersion: __t.string().name("memory_snapshot_version"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
