// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  roomId: __t.string().name("room_id"),
  intentId: __t.string().name("intent_id"),
  kind: __t.string(),
  status: __t.string(),
  targetRunId: __t.string().name("target_run_id"),
  createdAt: __t.timestamp().name("created_at"),
  consumedAt: __t.option(__t.timestamp()).name("consumed_at"),
});
