// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  nodeId: __t.string().name("node_id"),
  requestId: __t.string().name("request_id"),
  status: __t.string(),
  inboxDeliveryIdsJson: __t.string().name("inbox_delivery_ids_json"),
  manifestJson: __t.string().name("manifest_json"),
  jobId: __t.string().name("job_id"),
  requestedAtMs: __t.u64().name("requested_at_ms"),
  notBeforeMs: __t.u64().name("not_before_ms"),
  admittedAtMs: __t.u64().name("admitted_at_ms"),
  completedAtMs: __t.u64().name("completed_at_ms"),
  resultJson: __t.string().name("result_json"),
  lastError: __t.string().name("last_error"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  laneId: __t.string().name("lane_id"),
  roomId: __t.string().name("room_id"),
  runId: __t.string().name("run_id"),
});
