// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  nodeId: __t.string().name("node_id"),
  deliveryId: __t.string().name("delivery_id"),
  seq: __t.u64(),
  cause: __t.string(),
  sourceId: __t.string().name("source_id"),
  sourceVersion: __t.string().name("source_version"),
  sourceHash: __t.string().name("source_hash"),
  payloadReference: __t.string().name("payload_reference"),
  causalParentId: __t.string().name("causal_parent_id"),
  causalDepth: __t.u32().name("causal_depth"),
  status: __t.string(),
  wakeId: __t.string().name("wake_id"),
  itemJson: __t.string().name("item_json"),
  deliveredAtMs: __t.u64().name("delivered_at_ms"),
  consumedAt: __t.option(__t.timestamp()).name("consumed_at"),
  createdAt: __t.timestamp().name("created_at"),
  laneId: __t.string().name("lane_id"),
  roomId: __t.string().name("room_id"),
  runId: __t.string().name("run_id"),
});
