// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  jobId: __t.string().name("job_id"),
  command: __t.string(),
  lane: __t.string(),
  payloadJson: __t.string().name("payload_json"),
  by: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  consumedAt: __t.option(__t.timestamp()).name("consumed_at"),
  consumedBy: __t.string().name("consumed_by"),
});
