// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  roomId: __t.string().name("room_id"),
  runId: __t.string().name("run_id"),
  taskId: __t.string().name("task_id"),
  nodeId: __t.string().name("node_id"),
  fence: __t.u64(),
  provider: __t.string(),
  model: __t.string(),
  status: __t.string(),
  reservedCostMicros: __t.u64().name("reserved_cost_micros"),
  actualCostMicros: __t.u64().name("actual_cost_micros"),
  reservedTokens: __t.u64().name("reserved_tokens"),
  actualTokens: __t.u64().name("actual_tokens"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
