// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  roomId: __t.string().name("room_id"),
  runId: __t.string().name("run_id"),
  artifactId: __t.string().name("artifact_id"),
  updateId: __t.string().name("update_id"),
  taskId: __t.string().name("task_id"),
  nodeId: __t.string().name("node_id"),
  fence: __t.u64(),
  frontierVersion: __t.string().name("frontier_version"),
  topologyVersion: __t.string().name("topology_version"),
  catalogVersion: __t.string().name("catalog_version"),
  runtimeBindingEpoch: __t.u64().name("runtime_binding_epoch"),
  updateBase64: __t.string().name("update_base_64"),
  updateBytes: __t.u32().name("update_bytes"),
  createdAt: __t.timestamp().name("created_at"),
});
