// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  taskId: __t.string().name("task_id"),
  semanticKey: __t.string().name("semantic_key"),
  definitionHash: __t.string().name("definition_hash"),
  definitionJson: __t.string().name("definition_json"),
  nodeId: __t.string().name("node_id"),
  capability: __t.string(),
  objective: __t.string(),
  status: __t.string(),
  parentTaskId: __t.string().name("parent_task_id"),
  depth: __t.u32(),
  attempt: __t.u32(),
  maxAttempts: __t.u32().name("max_attempts"),
  leaseOwner: __t.option(__t.identity()).name("lease_owner"),
  leaseFence: __t.u64().name("lease_fence"),
  leaseUntil: __t.option(__t.timestamp()).name("lease_until"),
  availableAt: __t.timestamp().name("available_at"),
  lastError: __t.string().name("last_error"),
  outcomeId: __t.string().name("outcome_id"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
