// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  partId: __t.string().name("part_id"),
  planVersion: __t.string().name("plan_version"),
  ordinal: __t.u32(),
  kind: __t.string(),
  role: __t.string(),
  label: __t.string(),
  artistName: __t.string().name("artist_name"),
  focus: __t.string(),
  objective: __t.string(),
  compositionRole: __t.string().name("composition_role"),
  paintMode: __t.string().name("paint_mode"),
  coordinatesWithJson: __t.string().name("coordinates_with_json"),
  needsJson: __t.string().name("needs_json"),
  outputKey: __t.string().name("output_key"),
  regionJson: __t.string().name("region_json"),
  maxFootprintJson: __t.string().name("max_footprint_json"),
  protectedAnchorsJson: __t.string().name("protected_anchors_json"),
  allowBleed: __t.bool().name("allow_bleed"),
  layerBase: __t.u32().name("layer_base"),
  minObjects: __t.u32().name("min_objects"),
  maxObjects: __t.u32().name("max_objects"),
  createdAt: __t.timestamp().name("created_at"),
});
