// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  sceneHash: __t.string().name("scene_hash"),
  agentId: __t.string().name("agent_id"),
  verdict: __t.string(),
  qualityStatus: __t.string().name("quality_status"),
  scope: __t.string(),
  scoresJson: __t.string().name("scores_json"),
  checksJson: __t.string().name("checks_json"),
  notesJson: __t.string().name("notes_json"),
  createdAt: __t.timestamp().name("created_at"),
});
