// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  runId: __t.string().name("run_id"),
  patchId: __t.string().name("patch_id"),
  objectId: __t.string().name("object_id"),
  semanticId: __t.string().name("semantic_id"),
  ownerAgentId: __t.string().name("owner_agent_id"),
  taskId: __t.string().name("task_id"),
  partId: __t.string().name("part_id"),
  objectType: __t.string().name("object_type"),
  geometryJson: __t.string().name("geometry_json"),
  styleJson: __t.string().name("style_json"),
  layer: __t.u32(),
  rank: __t.u32(),
  active: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
