// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  streamId: __t.string().name("stream_id"),
  seq: __t.u64(),
  receiptId: __t.string().name("receipt_id"),
  occurredAtMs: __t.u64().name("occurred_at_ms"),
  prevHash: __t.string().name("prev_hash"),
  hash: __t.string(),
  bodyJson: __t.string().name("body_json"),
  hintsJson: __t.string().name("hints_json"),
  createdAt: __t.timestamp().name("created_at"),
});
