// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  patchId: __t.string().primaryKey().name("patch_id"),
  runId: __t.string().name("run_id"),
  partId: __t.string().name("part_id"),
  planVersion: __t.string().name("plan_version"),
  agentId: __t.string().name("agent_id"),
  taskKey: __t.string().name("task_key"),
  taskId: __t.string().name("task_id"),
  supersedesPatchId: __t.string().name("supersedes_patch_id"),
  contentRef: __t.string().name("content_ref"),
  contentHash: __t.string().name("content_hash"),
  updateHash: __t.string().name("update_hash"),
  baseSceneHash: __t.string().name("base_scene_hash"),
  patchJson: __t.string().name("patch_json"),
  objectCount: __t.u32().name("object_count"),
  active: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
});
