// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  runId: __t.string().primaryKey().name("run_id"),
  planVersion: __t.string().name("plan_version"),
  planHash: __t.string().name("plan_hash"),
  schemaVersion: __t.u32().name("schema_version"),
  width: __t.u32(),
  height: __t.u32(),
  painterCount: __t.u32().name("painter_count"),
  subject: __t.string(),
  artDirection: __t.string().name("art_direction"),
  focalBoundsJson: __t.string().name("focal_bounds_json"),
  anchorsJson: __t.string().name("anchors_json"),
  paletteJson: __t.string().name("palette_json"),
  partsJson: __t.string().name("parts_json"),
  planJson: __t.string().name("plan_json"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
