// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  workspaceId: __t.string().primaryKey().name("workspace_id"),
  jobsInWindow: __t.u32().name("jobs_in_window"),
  activeJobs: __t.u32().name("active_jobs"),
  totalJobs: __t.u64().name("total_jobs"),
  maxJobsInWindow: __t.u32().name("max_jobs_in_window"),
  maxActiveJobs: __t.u32().name("max_active_jobs"),
  windowStartedAt: __t.timestamp().name("window_started_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
