// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  artifactId: __t.string(),
  updateId: __t.string(),
  taskId: __t.string(),
  nodeId: __t.string(),
  fence: __t.u64(),
  frontierVersion: __t.string(),
  topologyVersion: __t.string(),
  catalogVersion: __t.string(),
  runtimeBindingEpoch: __t.u64(),
  updateBase64: __t.string(),
};
