// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CanvasActivity = __t.object("CanvasActivity", {
  id: __t.string(),
  runId: __t.string(),
  seq: __t.u64(),
  kind: __t.string(),
  agentId: __t.string(),
  agentName: __t.string(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type CanvasActivity = __Infer<typeof CanvasActivity>;

export const CanvasActivityProjection = __t.object("CanvasActivityProjection", {
  id: __t.string(),
  runId: __t.string(),
  seq: __t.u64(),
  kind: __t.string(),
  agentId: __t.string(),
  agentName: __t.string(),
  summary: __t.string(),
  createdAt: __t.timestamp(),
});
export type CanvasActivityProjection = __Infer<typeof CanvasActivityProjection>;

export const CanvasAgent = __t.object("CanvasAgent", {
  id: __t.string(),
  runId: __t.string(),
  agentId: __t.string(),
  name: __t.string(),
  role: __t.string(),
  group: __t.string(),
  focus: __t.string(),
  assignment: __t.string(),
  model: __t.string(),
  status: __t.string(),
  taskId: __t.string(),
  metadataJson: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CanvasAgent = __Infer<typeof CanvasAgent>;

export const CanvasAgentProjection = __t.object("CanvasAgentProjection", {
  id: __t.string(),
  runId: __t.string(),
  agentId: __t.string(),
  name: __t.string(),
  role: __t.string(),
  group: __t.string(),
  focus: __t.string(),
  assignment: __t.string(),
  model: __t.string(),
  status: __t.string(),
  taskId: __t.string(),
  metadataJson: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CanvasAgentProjection = __Infer<typeof CanvasAgentProjection>;

export const CanvasFleetRunProjection = __t.object("CanvasFleetRunProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  prompt: __t.string(),
  status: __t.string(),
  desiredAgents: __t.u32(),
  maxInflight: __t.u32(),
  objectCount: __t.u32(),
  activeAgents: __t.u32(),
  totalAgents: __t.u32(),
  totalTasks: __t.u32(),
  completedTasks: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CanvasFleetRunProjection = __Infer<typeof CanvasFleetRunProjection>;

export const CanvasReplayStepProjection = __t.object("CanvasReplayStepProjection", {
  id: __t.string(),
  runId: __t.string(),
  seq: __t.u64(),
  kind: __t.string(),
  agentId: __t.string(),
  label: __t.string(),
  patchId: __t.string(),
  supersedesPatchId: __t.string(),
  partId: __t.string(),
  status: __t.string(),
  objectCount: __t.u32(),
  createdAt: __t.timestamp(),
});
export type CanvasReplayStepProjection = __Infer<typeof CanvasReplayStepProjection>;

export const CanvasRun = __t.object("CanvasRun", {
  id: __t.string(),
  owner: __t.identity(),
  requestKey: __t.string(),
  prompt: __t.string(),
  status: __t.string(),
  desiredAgents: __t.u32(),
  maxInflight: __t.u32(),
  nextReceiptSeq: __t.u64(),
  headReceiptHash: __t.string(),
  budgetMicros: __t.u64(),
  reservedMicros: __t.u64(),
  spentMicros: __t.u64(),
  sceneHash: __t.string(),
  objectCount: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CanvasRun = __Infer<typeof CanvasRun>;

export const CanvasRunDetail = __t.object("CanvasRunDetail", {
  runId: __t.string(),
  uiStatus: __t.string(),
  statusNote: __t.string(),
  modelRoutingJson: __t.string(),
  configJson: __t.string(),
  workflowId: __t.string(),
  workflowVersion: __t.string(),
  promptHash: __t.string(),
  promptPath: __t.string(),
  planVersion: __t.string(),
  reviewSceneHash: __t.string(),
  reviewVerdict: __t.string(),
  qualityStatus: __t.string(),
  totalTasks: __t.u32(),
  completedTasks: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CanvasRunDetail = __Infer<typeof CanvasRunDetail>;

export const CanvasRunProjection = __t.object("CanvasRunProjection", {
  id: __t.string(),
  owner: __t.identity(),
  prompt: __t.string(),
  status: __t.string(),
  desiredAgents: __t.u32(),
  maxInflight: __t.u32(),
  nextReceiptSeq: __t.u64(),
  headReceiptHash: __t.string(),
  budgetMicros: __t.u64(),
  reservedMicros: __t.u64(),
  spentMicros: __t.u64(),
  sceneHash: __t.string(),
  objectCount: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CanvasRunProjection = __Infer<typeof CanvasRunProjection>;

export const CanvasRunUiProjection = __t.object("CanvasRunUiProjection", {
  id: __t.string(),
  prompt: __t.string(),
  status: __t.string(),
  uiStatus: __t.string(),
  statusNote: __t.string(),
  desiredAgents: __t.u32(),
  maxInflight: __t.u32(),
  sceneHash: __t.string(),
  objectCount: __t.u32(),
  modelRoutingJson: __t.string(),
  configJson: __t.string(),
  workflowId: __t.string(),
  workflowVersion: __t.string(),
  planVersion: __t.string(),
  reviewSceneHash: __t.string(),
  reviewVerdict: __t.string(),
  qualityStatus: __t.string(),
  totalTasks: __t.u32(),
  completedTasks: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CanvasRunUiProjection = __Infer<typeof CanvasRunUiProjection>;

export const CanvasTaskStatus = __t.object("CanvasTaskStatus", {
  id: __t.string(),
  runId: __t.string(),
  taskId: __t.string(),
  delegationId: __t.string(),
  agentId: __t.string(),
  capability: __t.string(),
  objective: __t.string(),
  parentTaskId: __t.string(),
  planId: __t.string(),
  planVersion: __t.string(),
  status: __t.string(),
  attempt: __t.u32(),
  needsJson: __t.string(),
  providesJson: __t.string(),
  inputVersionsJson: __t.string(),
  artifactIdsJson: __t.string(),
  error: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CanvasTaskStatus = __Infer<typeof CanvasTaskStatus>;

export const CanvasTaskStatusProjection = __t.object("CanvasTaskStatusProjection", {
  id: __t.string(),
  runId: __t.string(),
  taskId: __t.string(),
  delegationId: __t.string(),
  agentId: __t.string(),
  capability: __t.string(),
  objective: __t.string(),
  parentTaskId: __t.string(),
  planId: __t.string(),
  planVersion: __t.string(),
  status: __t.string(),
  attempt: __t.u32(),
  needsJson: __t.string(),
  providesJson: __t.string(),
  inputVersionsJson: __t.string(),
  artifactIdsJson: __t.string(),
  error: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CanvasTaskStatusProjection = __Infer<typeof CanvasTaskStatusProjection>;

export const CanvasWorkspaceRun = __t.object("CanvasWorkspaceRun", {
  runId: __t.string(),
  workspaceId: __t.string(),
  createdAt: __t.timestamp(),
});
export type CanvasWorkspaceRun = __Infer<typeof CanvasWorkspaceRun>;

export const CodingActiveRuntimeBindingProjection = __t.object("CodingActiveRuntimeBindingProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  nodeId: __t.string(),
  bindingId: __t.string(),
  epoch: __t.u64(),
  topologyVersion: __t.string(),
  runtimeKind: __t.string(),
  model: __t.string(),
  reasoningEffort: __t.string(),
  createdAt: __t.timestamp(),
});
export type CodingActiveRuntimeBindingProjection = __Infer<typeof CodingActiveRuntimeBindingProjection>;

export const CodingExecutionSummaryProjection = __t.object("CodingExecutionSummaryProjection", {
  runId: __t.string(),
  workspaceId: __t.string(),
  kind: __t.string(),
  status: __t.string(),
  graphVersion: __t.u64(),
  totalTasks: __t.u32(),
  readyTasks: __t.u32(),
  blockedTasks: __t.u32(),
  inflightTasks: __t.u32(),
  acceptedTasks: __t.u32(),
  failedTasks: __t.u32(),
  canceledTasks: __t.u32(),
  skippedTasks: __t.u32(),
  terminalReason: __t.string(),
  updatedAt: __t.timestamp(),
});
export type CodingExecutionSummaryProjection = __Infer<typeof CodingExecutionSummaryProjection>;

export const CodingPublicRoomProjection = __t.object("CodingPublicRoomProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  kind: __t.string(),
  status: __t.string(),
  activeRunId: __t.string(),
  certifiedCheckpointId: __t.string(),
  nextTimelineSeq: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CodingPublicRoomProjection = __Infer<typeof CodingPublicRoomProjection>;

export const CodingRoom = __t.object("CodingRoom", {
  id: __t.string(),
  workspaceId: __t.string(),
  codingWorkspaceId: __t.string(),
  roomId: __t.string(),
  conversationId: __t.string(),
  streamId: __t.string(),
  title: __t.string(),
  state: __t.string(),
  firstMessageId: __t.string(),
  messageCount: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CodingRoom = __Infer<typeof CodingRoom>;

export const CodingRoomProjection = __t.object("CodingRoomProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  codingWorkspaceId: __t.string(),
  roomId: __t.string(),
  conversationId: __t.string(),
  streamId: __t.string(),
  title: __t.string(),
  state: __t.string(),
  firstMessageId: __t.string(),
  messageCount: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CodingRoomProjection = __Infer<typeof CodingRoomProjection>;

export const CodingRoomTimelinePageRequest = __t.object("CodingRoomTimelinePageRequest", {
  id: __t.string(),
  member: __t.identity(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  beforeSeq: __t.u64(),
  requestedAt: __t.timestamp(),
  selectionId: __t.string(),
  expiresAt: __t.option(__t.timestamp()),
});
export type CodingRoomTimelinePageRequest = __Infer<typeof CodingRoomTimelinePageRequest>;

export const CodingRoomTimelineSelectionExpiration = __t.object("CodingRoomTimelineSelectionExpiration", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  requestId: __t.string(),
  expiresAtMicros: __t.u64(),
});
export type CodingRoomTimelineSelectionExpiration = __Infer<typeof CodingRoomTimelineSelectionExpiration>;

export const CodingRunTaskProjection = __t.object("CodingRunTaskProjection", {
  id: __t.string(),
  runId: __t.string(),
  taskId: __t.string(),
  nodeId: __t.string(),
  capability: __t.string(),
  status: __t.string(),
  attempt: __t.u32(),
  failureCategory: __t.string(),
  failureReason: __t.string(),
  updatedAt: __t.timestamp(),
});
export type CodingRunTaskProjection = __Infer<typeof CodingRunTaskProjection>;

export const CodingSelectedRoomTimelineProjection = __t.object("CodingSelectedRoomTimelineProjection", {
  selectionRowId: __t.string(),
  selectionId: __t.string(),
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  seq: __t.u64(),
  kind: __t.string(),
  taskId: __t.string(),
  nodeId: __t.string(),
  entryJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type CodingSelectedRoomTimelineProjection = __Infer<typeof CodingSelectedRoomTimelineProjection>;

export const CodingTaskOutputReferenceProjection = __t.object("CodingTaskOutputReferenceProjection", {
  id: __t.string(),
  runId: __t.string(),
  taskKey: __t.string(),
  taskId: __t.string(),
  outcomeId: __t.string(),
  artifactId: __t.string(),
  outputKey: __t.string(),
  createdAt: __t.timestamp(),
});
export type CodingTaskOutputReferenceProjection = __Infer<typeof CodingTaskOutputReferenceProjection>;

export const EventStream = __t.object("EventStream", {
  id: __t.string(),
  workspaceId: __t.string(),
  kind: __t.string(),
  nextSeq: __t.u64(),
  headHash: __t.string(),
  receiptCount: __t.u64(),
  parentStreamId: __t.string(),
  forkAt: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type EventStream = __Infer<typeof EventStream>;

export const EventStreamProjection = __t.object("EventStreamProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  streamId: __t.string(),
  kind: __t.string(),
  headHash: __t.string(),
  receiptCount: __t.u64(),
  parentStreamId: __t.string(),
  forkAt: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type EventStreamProjection = __Infer<typeof EventStreamProjection>;

export const MyCanvasActivity = __t.object("MyCanvasActivity", {});
export type MyCanvasActivity = __Infer<typeof MyCanvasActivity>;

export const MyCanvasAgents = __t.object("MyCanvasAgents", {});
export type MyCanvasAgents = __Infer<typeof MyCanvasAgents>;

export const MyCanvasFleetRuns = __t.object("MyCanvasFleetRuns", {});
export type MyCanvasFleetRuns = __Infer<typeof MyCanvasFleetRuns>;

export const MyCanvasReplaySteps = __t.object("MyCanvasReplaySteps", {});
export type MyCanvasReplaySteps = __Infer<typeof MyCanvasReplaySteps>;

export const MyCanvasRunUi = __t.object("MyCanvasRunUi", {});
export type MyCanvasRunUi = __Infer<typeof MyCanvasRunUi>;

export const MyCanvasRuns = __t.object("MyCanvasRuns", {});
export type MyCanvasRuns = __Infer<typeof MyCanvasRuns>;

export const MyCanvasTaskStatuses = __t.object("MyCanvasTaskStatuses", {});
export type MyCanvasTaskStatuses = __Infer<typeof MyCanvasTaskStatuses>;

export const MyClaimableRosterTasks = __t.object("MyClaimableRosterTasks", {});
export type MyClaimableRosterTasks = __Infer<typeof MyClaimableRosterTasks>;

export const MyCodingActiveRuntimeBindingsWindow = __t.object("MyCodingActiveRuntimeBindingsWindow", {});
export type MyCodingActiveRuntimeBindingsWindow = __Infer<typeof MyCodingActiveRuntimeBindingsWindow>;

export const MyCodingCollaborationSummariesWindow = __t.object("MyCodingCollaborationSummariesWindow", {});
export type MyCodingCollaborationSummariesWindow = __Infer<typeof MyCodingCollaborationSummariesWindow>;

export const MyCodingContextFrontiersWindow = __t.object("MyCodingContextFrontiersWindow", {});
export type MyCodingContextFrontiersWindow = __Infer<typeof MyCodingContextFrontiersWindow>;

export const MyCodingControlIntentDeliveriesWindow = __t.object("MyCodingControlIntentDeliveriesWindow", {});
export type MyCodingControlIntentDeliveriesWindow = __Infer<typeof MyCodingControlIntentDeliveriesWindow>;

export const MyCodingExecutionSummariesWindow = __t.object("MyCodingExecutionSummariesWindow", {});
export type MyCodingExecutionSummariesWindow = __Infer<typeof MyCodingExecutionSummariesWindow>;

export const MyCodingParticipantProfilesWindow = __t.object("MyCodingParticipantProfilesWindow", {});
export type MyCodingParticipantProfilesWindow = __Infer<typeof MyCodingParticipantProfilesWindow>;

export const MyCodingRoomNodesWindow = __t.object("MyCodingRoomNodesWindow", {});
export type MyCodingRoomNodesWindow = __Infer<typeof MyCodingRoomNodesWindow>;

export const MyCodingRoomTimeline = __t.object("MyCodingRoomTimeline", {});
export type MyCodingRoomTimeline = __Infer<typeof MyCodingRoomTimeline>;

export const MyCodingRoomTimelinePage = __t.object("MyCodingRoomTimelinePage", {});
export type MyCodingRoomTimelinePage = __Infer<typeof MyCodingRoomTimelinePage>;

export const MyCodingRoomTimelineWindow = __t.object("MyCodingRoomTimelineWindow", {});
export type MyCodingRoomTimelineWindow = __Infer<typeof MyCodingRoomTimelineWindow>;

export const MyCodingRooms = __t.object("MyCodingRooms", {});
export type MyCodingRooms = __Infer<typeof MyCodingRooms>;

export const MyCodingRoomsWindow = __t.object("MyCodingRoomsWindow", {});
export type MyCodingRoomsWindow = __Infer<typeof MyCodingRoomsWindow>;

export const MyCodingRunTaskEdgesWindow = __t.object("MyCodingRunTaskEdgesWindow", {});
export type MyCodingRunTaskEdgesWindow = __Infer<typeof MyCodingRunTaskEdgesWindow>;

export const MyCodingRunTaskOutputReferencesWindow = __t.object("MyCodingRunTaskOutputReferencesWindow", {});
export type MyCodingRunTaskOutputReferencesWindow = __Infer<typeof MyCodingRunTaskOutputReferencesWindow>;

export const MyCodingRunTasksWindow = __t.object("MyCodingRunTasksWindow", {});
export type MyCodingRunTasksWindow = __Infer<typeof MyCodingRunTasksWindow>;

export const MyEventStreams = __t.object("MyEventStreams", {});
export type MyEventStreams = __Infer<typeof MyEventStreams>;

export const MyReceipts = __t.object("MyReceipts", {});
export type MyReceipts = __Infer<typeof MyReceipts>;

export const MyRosterCollaborationSummaries = __t.object("MyRosterCollaborationSummaries", {});
export type MyRosterCollaborationSummaries = __Infer<typeof MyRosterCollaborationSummaries>;

export const MyRosterContextFrontiers = __t.object("MyRosterContextFrontiers", {});
export type MyRosterContextFrontiers = __Infer<typeof MyRosterContextFrontiers>;

export const MyRosterControlIntentDeliveries = __t.object("MyRosterControlIntentDeliveries", {});
export type MyRosterControlIntentDeliveries = __Infer<typeof MyRosterControlIntentDeliveries>;

export const MyRosterControlIntents = __t.object("MyRosterControlIntents", {});
export type MyRosterControlIntents = __Infer<typeof MyRosterControlIntents>;

export const MyRosterExecutionSummaries = __t.object("MyRosterExecutionSummaries", {});
export type MyRosterExecutionSummaries = __Infer<typeof MyRosterExecutionSummaries>;

export const MyRosterJobCommands = __t.object("MyRosterJobCommands", {});
export type MyRosterJobCommands = __Infer<typeof MyRosterJobCommands>;

export const MyRosterJobEvents = __t.object("MyRosterJobEvents", {});
export type MyRosterJobEvents = __Infer<typeof MyRosterJobEvents>;

export const MyRosterJobRequests = __t.object("MyRosterJobRequests", {});
export type MyRosterJobRequests = __Infer<typeof MyRosterJobRequests>;

export const MyRosterJobs = __t.object("MyRosterJobs", {});
export type MyRosterJobs = __Infer<typeof MyRosterJobs>;

export const MyRosterModelReservations = __t.object("MyRosterModelReservations", {});
export type MyRosterModelReservations = __Infer<typeof MyRosterModelReservations>;

export const MyRosterNodeCommitments = __t.object("MyRosterNodeCommitments", {});
export type MyRosterNodeCommitments = __Infer<typeof MyRosterNodeCommitments>;

export const MyRosterNodeContinuities = __t.object("MyRosterNodeContinuities", {});
export type MyRosterNodeContinuities = __Infer<typeof MyRosterNodeContinuities>;

export const MyRosterNodeContinuityEvents = __t.object("MyRosterNodeContinuityEvents", {});
export type MyRosterNodeContinuityEvents = __Infer<typeof MyRosterNodeContinuityEvents>;

export const MyRosterNodeInboxItems = __t.object("MyRosterNodeInboxItems", {});
export type MyRosterNodeInboxItems = __Infer<typeof MyRosterNodeInboxItems>;

export const MyRosterNodeWakes = __t.object("MyRosterNodeWakes", {});
export type MyRosterNodeWakes = __Infer<typeof MyRosterNodeWakes>;

export const MyRosterParticipantProfiles = __t.object("MyRosterParticipantProfiles", {});
export type MyRosterParticipantProfiles = __Infer<typeof MyRosterParticipantProfiles>;

export const MyRosterProjectionOutbox = __t.object("MyRosterProjectionOutbox", {});
export type MyRosterProjectionOutbox = __Infer<typeof MyRosterProjectionOutbox>;

export const MyRosterRoomNodes = __t.object("MyRosterRoomNodes", {});
export type MyRosterRoomNodes = __Infer<typeof MyRosterRoomNodes>;

export const MyRosterRoomTimelineEntries = __t.object("MyRosterRoomTimelineEntries", {});
export type MyRosterRoomTimelineEntries = __Infer<typeof MyRosterRoomTimelineEntries>;

export const MyRosterRooms = __t.object("MyRosterRooms", {});
export type MyRosterRooms = __Infer<typeof MyRosterRooms>;

export const MyRosterRuntimeBindings = __t.object("MyRosterRuntimeBindings", {});
export type MyRosterRuntimeBindings = __Infer<typeof MyRosterRuntimeBindings>;

export const MyRosterSharedWorkspaceCheckpoints = __t.object("MyRosterSharedWorkspaceCheckpoints", {});
export type MyRosterSharedWorkspaceCheckpoints = __Infer<typeof MyRosterSharedWorkspaceCheckpoints>;

export const MyRosterSharedWorkspaceUpdates = __t.object("MyRosterSharedWorkspaceUpdates", {});
export type MyRosterSharedWorkspaceUpdates = __Infer<typeof MyRosterSharedWorkspaceUpdates>;

export const MyRosterTaskContextManifests = __t.object("MyRosterTaskContextManifests", {});
export type MyRosterTaskContextManifests = __Infer<typeof MyRosterTaskContextManifests>;

export const MyRosterTaskEdges = __t.object("MyRosterTaskEdges", {});
export type MyRosterTaskEdges = __Infer<typeof MyRosterTaskEdges>;

export const MyRosterTaskExpansions = __t.object("MyRosterTaskExpansions", {});
export type MyRosterTaskExpansions = __Infer<typeof MyRosterTaskExpansions>;

export const MyRosterTaskOutcomes = __t.object("MyRosterTaskOutcomes", {});
export type MyRosterTaskOutcomes = __Infer<typeof MyRosterTaskOutcomes>;

export const MyRosterTaskOutputReferences = __t.object("MyRosterTaskOutputReferences", {});
export type MyRosterTaskOutputReferences = __Infer<typeof MyRosterTaskOutputReferences>;

export const MyRosterTasks = __t.object("MyRosterTasks", {});
export type MyRosterTasks = __Infer<typeof MyRosterTasks>;

export const MyRosterWorkerCapabilities = __t.object("MyRosterWorkerCapabilities", {});
export type MyRosterWorkerCapabilities = __Infer<typeof MyRosterWorkerCapabilities>;

export const MyRosterWorkspaceNodes = __t.object("MyRosterWorkspaceNodes", {});
export type MyRosterWorkspaceNodes = __Infer<typeof MyRosterWorkspaceNodes>;

export const MyRunMembers = __t.object("MyRunMembers", {});
export type MyRunMembers = __Infer<typeof MyRunMembers>;

export const MySceneObjects = __t.object("MySceneObjects", {});
export type MySceneObjects = __Infer<typeof MySceneObjects>;

export const MyScenePatches = __t.object("MyScenePatches", {});
export type MyScenePatches = __Infer<typeof MyScenePatches>;

export const MyScenePlan = __t.object("MyScenePlan", {});
export type MyScenePlan = __Infer<typeof MyScenePlan>;

export const MyScenePlanParts = __t.object("MyScenePlanParts", {});
export type MyScenePlanParts = __Infer<typeof MyScenePlanParts>;

export const MySceneReviews = __t.object("MySceneReviews", {});
export type MySceneReviews = __Infer<typeof MySceneReviews>;

export const MyStreamBranches = __t.object("MyStreamBranches", {});
export type MyStreamBranches = __Infer<typeof MyStreamBranches>;

export const MyStreamReceipts = __t.object("MyStreamReceipts", {});
export type MyStreamReceipts = __Infer<typeof MyStreamReceipts>;

export const MyWorkspaceUsage = __t.object("MyWorkspaceUsage", {});
export type MyWorkspaceUsage = __Infer<typeof MyWorkspaceUsage>;

export const MyWorkspaces = __t.object("MyWorkspaces", {});
export type MyWorkspaces = __Infer<typeof MyWorkspaces>;

export const Receipt = __t.object("Receipt", {
  id: __t.string(),
  runId: __t.string(),
  seq: __t.u64(),
  eventId: __t.string(),
  kind: __t.string(),
  actor: __t.identity(),
  agentId: __t.string(),
  payloadJson: __t.string(),
  prevHash: __t.string(),
  hash: __t.string(),
  createdAt: __t.timestamp(),
});
export type Receipt = __Infer<typeof Receipt>;

export const ReceiptProjection = __t.object("ReceiptProjection", {
  id: __t.string(),
  runId: __t.string(),
  seq: __t.u64(),
  eventId: __t.string(),
  kind: __t.string(),
  actor: __t.identity(),
  agentId: __t.string(),
  payloadJson: __t.string(),
  prevHash: __t.string(),
  hash: __t.string(),
  createdAt: __t.timestamp(),
});
export type ReceiptProjection = __Infer<typeof ReceiptProjection>;

export const RosterCollaborationSummaryProjection = __t.object("RosterCollaborationSummaryProjection", {
  runId: __t.string(),
  workspaceId: __t.string(),
  proposalCount: __t.u32(),
  responseCount: __t.u32(),
  endorsementCount: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type RosterCollaborationSummaryProjection = __Infer<typeof RosterCollaborationSummaryProjection>;

export const RosterContextFrontier = __t.object("RosterContextFrontier", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  contextVersion: __t.string(),
  frontierVersion: __t.string(),
  topologyVersion: __t.string(),
  catalogVersion: __t.string(),
  bindingVersion: __t.string(),
  frontierJson: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterContextFrontier = __Infer<typeof RosterContextFrontier>;

export const RosterContextFrontierProjection = __t.object("RosterContextFrontierProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  contextVersion: __t.string(),
  frontierVersion: __t.string(),
  topologyVersion: __t.string(),
  catalogVersion: __t.string(),
  bindingVersion: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterContextFrontierProjection = __Infer<typeof RosterContextFrontierProjection>;

export const RosterExecution = __t.object("RosterExecution", {
  runId: __t.string(),
  protocolVersion: __t.string(),
  kind: __t.string(),
  workspaceId: __t.string(),
  receiptStreamId: __t.string(),
  status: __t.string(),
  policyJson: __t.string(),
  graphVersion: __t.u64(),
  nextEventSeq: __t.u64(),
  totalTasks: __t.u32(),
  readyTasks: __t.u32(),
  blockedTasks: __t.u32(),
  inflightTasks: __t.u32(),
  acceptedTasks: __t.u32(),
  failedTasks: __t.u32(),
  delegatedTasks: __t.u32(),
  canceledTasks: __t.u32(),
  skippedTasks: __t.u32(),
  contextBytes: __t.u64(),
  reservedCostMicros: __t.u64(),
  spentCostMicros: __t.u64(),
  usedTokens: __t.u64(),
  terminalReason: __t.string(),
  deadlineAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterExecution = __Infer<typeof RosterExecution>;

export const RosterExecutionDeadline = __t.object("RosterExecutionDeadline", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  runId: __t.string(),
  deadlineMicros: __t.u64(),
});
export type RosterExecutionDeadline = __Infer<typeof RosterExecutionDeadline>;

export const RosterExecutionEvent = __t.object("RosterExecutionEvent", {
  id: __t.string(),
  runId: __t.string(),
  seq: __t.u64(),
  kind: __t.string(),
  actor: __t.identity(),
  nodeId: __t.string(),
  payloadJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type RosterExecutionEvent = __Infer<typeof RosterExecutionEvent>;

export const RosterExecutionInitialization = __t.object("RosterExecutionInitialization", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  idempotencyKey: __t.string(),
  argumentsHash: __t.string(),
  createdAt: __t.timestamp(),
});
export type RosterExecutionInitialization = __Infer<typeof RosterExecutionInitialization>;

export const RosterExecutionSummaryProjection = __t.object("RosterExecutionSummaryProjection", {
  runId: __t.string(),
  protocolVersion: __t.string(),
  kind: __t.string(),
  workspaceId: __t.string(),
  receiptStreamId: __t.string(),
  status: __t.string(),
  policyJson: __t.string(),
  graphVersion: __t.u64(),
  totalTasks: __t.u32(),
  readyTasks: __t.u32(),
  blockedTasks: __t.u32(),
  inflightTasks: __t.u32(),
  acceptedTasks: __t.u32(),
  failedTasks: __t.u32(),
  delegatedTasks: __t.u32(),
  canceledTasks: __t.u32(),
  skippedTasks: __t.u32(),
  contextBytes: __t.u64(),
  reservedCostMicros: __t.u64(),
  spentCostMicros: __t.u64(),
  usedTokens: __t.u64(),
  terminalReason: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterExecutionSummaryProjection = __Infer<typeof RosterExecutionSummaryProjection>;

export const RosterJob = __t.object("RosterJob", {
  id: __t.string(),
  workspaceId: __t.string(),
  agentId: __t.string(),
  lane: __t.string(),
  sessionKey: __t.string(),
  singletonMode: __t.string(),
  payloadJson: __t.string(),
  status: __t.string(),
  attempt: __t.u32(),
  maxAttempts: __t.u32(),
  leaseOwner: __t.option(__t.identity()),
  leaseWorker: __t.string(),
  leaseFence: __t.u64(),
  leaseUntil: __t.option(__t.timestamp()),
  claimToken: __t.string(),
  availableAt: __t.timestamp(),
  lastError: __t.string(),
  resultJson: __t.string(),
  canceledReason: __t.string(),
  abortRequested: __t.bool(),
  nextEventSeq: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterJob = __Infer<typeof RosterJob>;

export const RosterJobCommand = __t.object("RosterJobCommand", {
  id: __t.string(),
  workspaceId: __t.string(),
  jobId: __t.string(),
  command: __t.string(),
  lane: __t.string(),
  payloadJson: __t.string(),
  by: __t.string(),
  createdAt: __t.timestamp(),
  consumedAt: __t.option(__t.timestamp()),
  consumedBy: __t.string(),
});
export type RosterJobCommand = __Infer<typeof RosterJobCommand>;

export const RosterJobCommandProjection = __t.object("RosterJobCommandProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  jobId: __t.string(),
  command: __t.string(),
  lane: __t.string(),
  payloadJson: __t.string(),
  by: __t.string(),
  createdAt: __t.timestamp(),
  consumedAt: __t.option(__t.timestamp()),
  consumedBy: __t.string(),
});
export type RosterJobCommandProjection = __Infer<typeof RosterJobCommandProjection>;

export const RosterJobEvent = __t.object("RosterJobEvent", {
  id: __t.string(),
  workspaceId: __t.string(),
  jobId: __t.string(),
  seq: __t.u64(),
  kind: __t.string(),
  eventJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type RosterJobEvent = __Infer<typeof RosterJobEvent>;

export const RosterJobEventProjection = __t.object("RosterJobEventProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  jobId: __t.string(),
  seq: __t.u64(),
  kind: __t.string(),
  eventJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type RosterJobEventProjection = __Infer<typeof RosterJobEventProjection>;

export const RosterJobLeaseExpiry = __t.object("RosterJobLeaseExpiry", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  jobId: __t.string(),
  fence: __t.u64(),
});
export type RosterJobLeaseExpiry = __Infer<typeof RosterJobLeaseExpiry>;

export const RosterJobProjection = __t.object("RosterJobProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  agentId: __t.string(),
  lane: __t.string(),
  sessionKey: __t.string(),
  singletonMode: __t.string(),
  payloadJson: __t.string(),
  status: __t.string(),
  attempt: __t.u32(),
  maxAttempts: __t.u32(),
  leaseOwner: __t.option(__t.identity()),
  leaseWorker: __t.string(),
  leaseFence: __t.u64(),
  leaseUntil: __t.option(__t.timestamp()),
  claimToken: __t.string(),
  availableAt: __t.timestamp(),
  lastError: __t.string(),
  resultJson: __t.string(),
  canceledReason: __t.string(),
  abortRequested: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterJobProjection = __Infer<typeof RosterJobProjection>;

export const RosterJobRequest = __t.object("RosterJobRequest", {
  id: __t.string(),
  workspaceId: __t.string(),
  requestId: __t.string(),
  requestedJobId: __t.string(),
  resolvedJobId: __t.string(),
  requestJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type RosterJobRequest = __Infer<typeof RosterJobRequest>;

export const RosterJobRequestProjection = __t.object("RosterJobRequestProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  requestId: __t.string(),
  requestedJobId: __t.string(),
  resolvedJobId: __t.string(),
  createdAt: __t.timestamp(),
});
export type RosterJobRequestProjection = __Infer<typeof RosterJobRequestProjection>;

export const RosterModelReservation = __t.object("RosterModelReservation", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  taskId: __t.string(),
  nodeId: __t.string(),
  fence: __t.u64(),
  provider: __t.string(),
  model: __t.string(),
  status: __t.string(),
  reservedCostMicros: __t.u64(),
  actualCostMicros: __t.u64(),
  reservedTokens: __t.u64(),
  actualTokens: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterModelReservation = __Infer<typeof RosterModelReservation>;

export const RosterNodeCommitment = __t.object("RosterNodeCommitment", {
  id: __t.string(),
  workspaceId: __t.string(),
  nodeId: __t.string(),
  commitmentId: __t.string(),
  objective: __t.string(),
  status: __t.string(),
  revision: __t.u64(),
  sourceId: __t.string(),
  updatedAtMs: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterNodeCommitment = __Infer<typeof RosterNodeCommitment>;

export const RosterNodeContinuity = __t.object("RosterNodeContinuity", {
  id: __t.string(),
  workspaceId: __t.string(),
  nodeId: __t.string(),
  status: __t.string(),
  revision: __t.u64(),
  nextInboxSeq: __t.u64(),
  nextEventSeq: __t.u64(),
  pendingInboxCount: __t.u32(),
  activeWakeId: __t.string(),
  lastWakeId: __t.string(),
  lastWakeAtMs: __t.u64(),
  wakeWindowStartedAtMs: __t.u64(),
  wakesInWindow: __t.u32(),
  memoryScopeId: __t.string(),
  memorySnapshotVersion: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterNodeContinuity = __Infer<typeof RosterNodeContinuity>;

export const RosterNodeContinuityEvent = __t.object("RosterNodeContinuityEvent", {
  id: __t.string(),
  workspaceId: __t.string(),
  nodeId: __t.string(),
  seq: __t.u64(),
  kind: __t.string(),
  eventJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type RosterNodeContinuityEvent = __Infer<typeof RosterNodeContinuityEvent>;

export const RosterNodeInboxItem = __t.object("RosterNodeInboxItem", {
  id: __t.string(),
  workspaceId: __t.string(),
  nodeId: __t.string(),
  deliveryId: __t.string(),
  seq: __t.u64(),
  cause: __t.string(),
  sourceId: __t.string(),
  sourceVersion: __t.string(),
  sourceHash: __t.string(),
  payloadReference: __t.string(),
  causalParentId: __t.string(),
  causalDepth: __t.u32(),
  status: __t.string(),
  wakeId: __t.string(),
  itemJson: __t.string(),
  deliveredAtMs: __t.u64(),
  consumedAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  laneId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
});
export type RosterNodeInboxItem = __Infer<typeof RosterNodeInboxItem>;

export const RosterNodeWake = __t.object("RosterNodeWake", {
  id: __t.string(),
  workspaceId: __t.string(),
  nodeId: __t.string(),
  requestId: __t.string(),
  status: __t.string(),
  inboxDeliveryIdsJson: __t.string(),
  manifestJson: __t.string(),
  jobId: __t.string(),
  requestedAtMs: __t.u64(),
  notBeforeMs: __t.u64(),
  admittedAtMs: __t.u64(),
  completedAtMs: __t.u64(),
  resultJson: __t.string(),
  lastError: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  laneId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
});
export type RosterNodeWake = __Infer<typeof RosterNodeWake>;

export const RosterNodeWakeSchedule = __t.object("RosterNodeWakeSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  wakeId: __t.string(),
});
export type RosterNodeWakeSchedule = __Infer<typeof RosterNodeWakeSchedule>;

export const RosterParticipantProfile = __t.object("RosterParticipantProfile", {
  id: __t.string(),
  workspaceId: __t.string(),
  nodeId: __t.string(),
  displayName: __t.string(),
  role: __t.string(),
  bio: __t.string(),
  skillsJson: __t.string(),
  capabilitiesJson: __t.string(),
  revision: __t.u64(),
  updatedBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterParticipantProfile = __Infer<typeof RosterParticipantProfile>;

export const RosterParticipantProfileProjection = __t.object("RosterParticipantProfileProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  nodeId: __t.string(),
  displayName: __t.string(),
  role: __t.string(),
  bio: __t.string(),
  skillsJson: __t.string(),
  capabilitiesJson: __t.string(),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterParticipantProfileProjection = __Infer<typeof RosterParticipantProfileProjection>;

export const RosterProjectionOutbox = __t.object("RosterProjectionOutbox", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  kind: __t.string(),
  payloadJson: __t.string(),
  status: __t.string(),
  attempt: __t.u32(),
  lastError: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterProjectionOutbox = __Infer<typeof RosterProjectionOutbox>;

export const RosterRoom = __t.object("RosterRoom", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomKey: __t.string(),
  kind: __t.string(),
  title: __t.string(),
  status: __t.string(),
  activeRunId: __t.string(),
  certifiedCheckpointId: __t.string(),
  nextTimelineSeq: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterRoom = __Infer<typeof RosterRoom>;

export const RosterRoomControlIntent = __t.object("RosterRoomControlIntent", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  intentId: __t.string(),
  kind: __t.string(),
  payloadJson: __t.string(),
  status: __t.string(),
  targetRunId: __t.string(),
  consumedBy: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  consumedAt: __t.option(__t.timestamp()),
});
export type RosterRoomControlIntent = __Infer<typeof RosterRoomControlIntent>;

export const RosterRoomControlIntentProjection = __t.object("RosterRoomControlIntentProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  intentId: __t.string(),
  kind: __t.string(),
  status: __t.string(),
  targetRunId: __t.string(),
  createdAt: __t.timestamp(),
  consumedAt: __t.option(__t.timestamp()),
});
export type RosterRoomControlIntentProjection = __Infer<typeof RosterRoomControlIntentProjection>;

export const RosterRoomNode = __t.object("RosterRoomNode", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  nodeId: __t.string(),
  name: __t.string(),
  capabilitiesJson: __t.string(),
  parentNodeId: __t.string(),
  nodeJson: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterRoomNode = __Infer<typeof RosterRoomNode>;

export const RosterRoomNodeProjection = __t.object("RosterRoomNodeProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  nodeId: __t.string(),
  name: __t.string(),
  capabilitiesJson: __t.string(),
  parentNodeId: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterRoomNodeProjection = __Infer<typeof RosterRoomNodeProjection>;

export const RosterRoomTimelineEntry = __t.object("RosterRoomTimelineEntry", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  seq: __t.u64(),
  kind: __t.string(),
  taskId: __t.string(),
  nodeId: __t.string(),
  entryJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type RosterRoomTimelineEntry = __Infer<typeof RosterRoomTimelineEntry>;

export const RosterRuntimeBinding = __t.object("RosterRuntimeBinding", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  nodeId: __t.string(),
  bindingId: __t.string(),
  epoch: __t.u64(),
  topologyVersion: __t.string(),
  runtimeJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type RosterRuntimeBinding = __Infer<typeof RosterRuntimeBinding>;

export const RosterSharedWorkspaceCheckpoint = __t.object("RosterSharedWorkspaceCheckpoint", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  artifactId: __t.string(),
  checkpointId: __t.string(),
  throughUpdateId: __t.string(),
  frontierVersion: __t.string(),
  topologyVersion: __t.string(),
  stateBase64: __t.string(),
  stateBytes: __t.u32(),
  createdAt: __t.timestamp(),
});
export type RosterSharedWorkspaceCheckpoint = __Infer<typeof RosterSharedWorkspaceCheckpoint>;

export const RosterSharedWorkspaceUpdate = __t.object("RosterSharedWorkspaceUpdate", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  artifactId: __t.string(),
  updateId: __t.string(),
  taskId: __t.string(),
  nodeId: __t.string(),
  fence: __t.u64(),
  frontierVersion: __t.string(),
  topologyVersion: __t.string(),
  catalogVersion: __t.string(),
  runtimeBindingEpoch: __t.u64(),
  updateBase64: __t.string(),
  updateBytes: __t.u32(),
  createdAt: __t.timestamp(),
});
export type RosterSharedWorkspaceUpdate = __Infer<typeof RosterSharedWorkspaceUpdate>;

export const RosterTaskContextManifest = __t.object("RosterTaskContextManifest", {
  id: __t.string(),
  workspaceId: __t.string(),
  roomId: __t.string(),
  runId: __t.string(),
  taskId: __t.string(),
  nodeId: __t.string(),
  attempt: __t.u32(),
  fence: __t.u64(),
  manifestId: __t.string(),
  contextVersion: __t.string(),
  frontierVersion: __t.string(),
  topologyVersion: __t.string(),
  catalogVersion: __t.string(),
  bindingVersion: __t.u64(),
  manifestJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type RosterTaskContextManifest = __Infer<typeof RosterTaskContextManifest>;

export const RosterTaskDefinition = __t.object("RosterTaskDefinition", {
  id: __t.string(),
  runId: __t.string(),
  taskId: __t.string(),
  semanticKey: __t.string(),
  definitionHash: __t.string(),
  definitionJson: __t.string(),
  nodeId: __t.string(),
  capability: __t.string(),
  objective: __t.string(),
  handlerKind: __t.string(),
  handlerVersion: __t.string(),
  acceptancePolicyId: __t.string(),
  acceptancePolicyVersion: __t.string(),
  resultJson: __t.string(),
  inputManifestJson: __t.string(),
  frontierVersion: __t.string(),
  topologyVersion: __t.string(),
  catalogVersion: __t.string(),
  runtimeBindingEpoch: __t.u64(),
  sideEffect: __t.string(),
  estimatedCostMicros: __t.u64(),
  contextBytes: __t.u64(),
  parentTaskId: __t.string(),
  depth: __t.u32(),
  status: __t.string(),
  attempt: __t.u32(),
  maxAttempts: __t.u32(),
  retryInitialBackoffMs: __t.u32(),
  retryMaximumBackoffMs: __t.u32(),
  timeoutMs: __t.u32(),
  availableAt: __t.timestamp(),
  leaseOwner: __t.option(__t.identity()),
  leaseFence: __t.u64(),
  leaseUntil: __t.option(__t.timestamp()),
  lastError: __t.string(),
  outcomeId: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterTaskDefinition = __Infer<typeof RosterTaskDefinition>;

export const RosterTaskEdge = __t.object("RosterTaskEdge", {
  id: __t.string(),
  runId: __t.string(),
  taskKey: __t.string(),
  prerequisiteTaskKey: __t.string(),
  condition: __t.string(),
  createdAt: __t.timestamp(),
});
export type RosterTaskEdge = __Infer<typeof RosterTaskEdge>;

export const RosterTaskExpansion = __t.object("RosterTaskExpansion", {
  id: __t.string(),
  runId: __t.string(),
  parentTaskKey: __t.string(),
  parentTaskId: __t.string(),
  publicationFence: __t.u64(),
  expansionKey: __t.string(),
  expansionSpecJson: __t.string(),
  childCount: __t.u32(),
  continuationTaskId: __t.string(),
  delegatedBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type RosterTaskExpansion = __Infer<typeof RosterTaskExpansion>;

export const RosterTaskJoin = __t.object("RosterTaskJoin", {
  taskKey: __t.string(),
  runId: __t.string(),
  kind: __t.string(),
  quorum: __t.u32(),
  totalDependencies: __t.u32(),
  acceptedDependencies: __t.u32(),
  terminalDependencies: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterTaskJoin = __Infer<typeof RosterTaskJoin>;

export const RosterTaskLeaseExpiry = __t.object("RosterTaskLeaseExpiry", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  taskKey: __t.string(),
  fence: __t.u64(),
});
export type RosterTaskLeaseExpiry = __Infer<typeof RosterTaskLeaseExpiry>;

export const RosterTaskOutcome = __t.object("RosterTaskOutcome", {
  outcomeId: __t.string(),
  runId: __t.string(),
  taskKey: __t.string(),
  definitionHash: __t.string(),
  outcomeJson: __t.string(),
  artifactsJson: __t.string(),
  usageJson: __t.string(),
  actualCostMicros: __t.u64(),
  totalTokens: __t.u64(),
  createdAt: __t.timestamp(),
});
export type RosterTaskOutcome = __Infer<typeof RosterTaskOutcome>;

export const RosterTaskOutputReference = __t.object("RosterTaskOutputReference", {
  id: __t.string(),
  runId: __t.string(),
  taskKey: __t.string(),
  taskId: __t.string(),
  outcomeId: __t.string(),
  artifactId: __t.string(),
  outputKey: __t.string(),
  referenceJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type RosterTaskOutputReference = __Infer<typeof RosterTaskOutputReference>;

export const RosterTaskProjection = __t.object("RosterTaskProjection", {
  id: __t.string(),
  runId: __t.string(),
  taskId: __t.string(),
  semanticKey: __t.string(),
  definitionHash: __t.string(),
  definitionJson: __t.string(),
  nodeId: __t.string(),
  capability: __t.string(),
  objective: __t.string(),
  status: __t.string(),
  parentTaskId: __t.string(),
  depth: __t.u32(),
  attempt: __t.u32(),
  maxAttempts: __t.u32(),
  leaseOwner: __t.option(__t.identity()),
  leaseFence: __t.u64(),
  leaseUntil: __t.option(__t.timestamp()),
  availableAt: __t.timestamp(),
  lastError: __t.string(),
  outcomeId: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterTaskProjection = __Infer<typeof RosterTaskProjection>;

export const RosterTaskRetryWake = __t.object("RosterTaskRetryWake", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  taskKey: __t.string(),
  availableAtMicros: __t.u64(),
});
export type RosterTaskRetryWake = __Infer<typeof RosterTaskRetryWake>;

export const RosterTaskSemanticKey = __t.object("RosterTaskSemanticKey", {
  id: __t.string(),
  runId: __t.string(),
  semanticKey: __t.string(),
  taskKey: __t.string(),
  createdAt: __t.timestamp(),
});
export type RosterTaskSemanticKey = __Infer<typeof RosterTaskSemanticKey>;

export const RosterWorkerCapability = __t.object("RosterWorkerCapability", {
  id: __t.string(),
  runId: __t.string(),
  worker: __t.identity(),
  capability: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type RosterWorkerCapability = __Infer<typeof RosterWorkerCapability>;

export const RosterWorkspace = __t.object("RosterWorkspace", {
  id: __t.string(),
  owner: __t.identity(),
  name: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterWorkspace = __Infer<typeof RosterWorkspace>;

export const RosterWorkspaceMember = __t.object("RosterWorkspaceMember", {
  id: __t.string(),
  workspaceId: __t.string(),
  member: __t.identity(),
  role: __t.string(),
  createdAt: __t.timestamp(),
});
export type RosterWorkspaceMember = __Infer<typeof RosterWorkspaceMember>;

export const RosterWorkspaceNode = __t.object("RosterWorkspaceNode", {
  id: __t.string(),
  workspaceId: __t.string(),
  nodeId: __t.string(),
  nodeRevision: __t.u64(),
  nodeJson: __t.string(),
  continuityPolicyJson: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type RosterWorkspaceNode = __Infer<typeof RosterWorkspaceNode>;

export const RosterWorkspaceUsage = __t.object("RosterWorkspaceUsage", {
  workspaceId: __t.string(),
  owner: __t.identity(),
  windowStartedAt: __t.timestamp(),
  jobsInWindow: __t.u32(),
  activeJobs: __t.u32(),
  totalJobs: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type RosterWorkspaceUsage = __Infer<typeof RosterWorkspaceUsage>;

export const RunMember = __t.object("RunMember", {
  id: __t.string(),
  runId: __t.string(),
  member: __t.identity(),
  role: __t.string(),
  createdAt: __t.timestamp(),
});
export type RunMember = __Infer<typeof RunMember>;

export const RunMemberProjection = __t.object("RunMemberProjection", {
  id: __t.string(),
  runId: __t.string(),
  member: __t.identity(),
  role: __t.string(),
  createdAt: __t.timestamp(),
});
export type RunMemberProjection = __Infer<typeof RunMemberProjection>;

export const SceneObject = __t.object("SceneObject", {
  id: __t.string(),
  runId: __t.string(),
  patchId: __t.string(),
  objectId: __t.string(),
  semanticId: __t.string(),
  ownerAgentId: __t.string(),
  taskId: __t.string(),
  partId: __t.string(),
  objectType: __t.string(),
  geometryJson: __t.string(),
  styleJson: __t.string(),
  layer: __t.u32(),
  rank: __t.u32(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SceneObject = __Infer<typeof SceneObject>;

export const SceneObjectProjection = __t.object("SceneObjectProjection", {
  id: __t.string(),
  runId: __t.string(),
  patchId: __t.string(),
  objectId: __t.string(),
  semanticId: __t.string(),
  ownerAgentId: __t.string(),
  taskId: __t.string(),
  partId: __t.string(),
  objectType: __t.string(),
  geometryJson: __t.string(),
  styleJson: __t.string(),
  layer: __t.u32(),
  rank: __t.u32(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type SceneObjectProjection = __Infer<typeof SceneObjectProjection>;

export const ScenePatch = __t.object("ScenePatch", {
  patchId: __t.string(),
  runId: __t.string(),
  partId: __t.string(),
  agentId: __t.string(),
  taskKey: __t.string(),
  supersedesPatchId: __t.string(),
  contentRef: __t.string(),
  contentHash: __t.string(),
  objectCount: __t.u32(),
  createdAt: __t.timestamp(),
});
export type ScenePatch = __Infer<typeof ScenePatch>;

export const ScenePatchData = __t.object("ScenePatchData", {
  patchId: __t.string(),
  runId: __t.string(),
  planVersion: __t.string(),
  baseSceneHash: __t.string(),
  partId: __t.string(),
  agentId: __t.string(),
  taskId: __t.string(),
  supersedesPatchId: __t.string(),
  contentRef: __t.string(),
  contentHash: __t.string(),
  updateHash: __t.string(),
  patchJson: __t.string(),
  objectCount: __t.u32(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
});
export type ScenePatchData = __Infer<typeof ScenePatchData>;

export const ScenePatchProjection = __t.object("ScenePatchProjection", {
  patchId: __t.string(),
  runId: __t.string(),
  partId: __t.string(),
  planVersion: __t.string(),
  agentId: __t.string(),
  taskKey: __t.string(),
  taskId: __t.string(),
  supersedesPatchId: __t.string(),
  contentRef: __t.string(),
  contentHash: __t.string(),
  updateHash: __t.string(),
  baseSceneHash: __t.string(),
  patchJson: __t.string(),
  objectCount: __t.u32(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
});
export type ScenePatchProjection = __Infer<typeof ScenePatchProjection>;

export const ScenePlan = __t.object("ScenePlan", {
  runId: __t.string(),
  planVersion: __t.string(),
  planHash: __t.string(),
  schemaVersion: __t.u32(),
  width: __t.u32(),
  height: __t.u32(),
  painterCount: __t.u32(),
  subject: __t.string(),
  artDirection: __t.string(),
  focalBoundsJson: __t.string(),
  anchorsJson: __t.string(),
  paletteJson: __t.string(),
  partsJson: __t.string(),
  planJson: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ScenePlan = __Infer<typeof ScenePlan>;

export const ScenePlanPart = __t.object("ScenePlanPart", {
  id: __t.string(),
  runId: __t.string(),
  partId: __t.string(),
  planVersion: __t.string(),
  ordinal: __t.u32(),
  kind: __t.string(),
  role: __t.string(),
  label: __t.string(),
  artistName: __t.string(),
  focus: __t.string(),
  objective: __t.string(),
  compositionRole: __t.string(),
  paintMode: __t.string(),
  coordinatesWithJson: __t.string(),
  needsJson: __t.string(),
  outputKey: __t.string(),
  regionJson: __t.string(),
  maxFootprintJson: __t.string(),
  protectedAnchorsJson: __t.string(),
  allowBleed: __t.bool(),
  layerBase: __t.u32(),
  minObjects: __t.u32(),
  maxObjects: __t.u32(),
  createdAt: __t.timestamp(),
});
export type ScenePlanPart = __Infer<typeof ScenePlanPart>;

export const ScenePlanPartProjection = __t.object("ScenePlanPartProjection", {
  id: __t.string(),
  runId: __t.string(),
  partId: __t.string(),
  planVersion: __t.string(),
  ordinal: __t.u32(),
  kind: __t.string(),
  role: __t.string(),
  label: __t.string(),
  artistName: __t.string(),
  focus: __t.string(),
  objective: __t.string(),
  compositionRole: __t.string(),
  paintMode: __t.string(),
  coordinatesWithJson: __t.string(),
  needsJson: __t.string(),
  outputKey: __t.string(),
  regionJson: __t.string(),
  maxFootprintJson: __t.string(),
  protectedAnchorsJson: __t.string(),
  allowBleed: __t.bool(),
  layerBase: __t.u32(),
  minObjects: __t.u32(),
  maxObjects: __t.u32(),
  createdAt: __t.timestamp(),
});
export type ScenePlanPartProjection = __Infer<typeof ScenePlanPartProjection>;

export const ScenePlanProjection = __t.object("ScenePlanProjection", {
  runId: __t.string(),
  planVersion: __t.string(),
  planHash: __t.string(),
  schemaVersion: __t.u32(),
  width: __t.u32(),
  height: __t.u32(),
  painterCount: __t.u32(),
  subject: __t.string(),
  artDirection: __t.string(),
  focalBoundsJson: __t.string(),
  anchorsJson: __t.string(),
  paletteJson: __t.string(),
  partsJson: __t.string(),
  planJson: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ScenePlanProjection = __Infer<typeof ScenePlanProjection>;

export const SceneReview = __t.object("SceneReview", {
  id: __t.string(),
  runId: __t.string(),
  sceneHash: __t.string(),
  agentId: __t.string(),
  verdict: __t.string(),
  qualityStatus: __t.string(),
  scope: __t.string(),
  scoresJson: __t.string(),
  checksJson: __t.string(),
  notesJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type SceneReview = __Infer<typeof SceneReview>;

export const SceneReviewProjection = __t.object("SceneReviewProjection", {
  id: __t.string(),
  runId: __t.string(),
  sceneHash: __t.string(),
  agentId: __t.string(),
  verdict: __t.string(),
  qualityStatus: __t.string(),
  scope: __t.string(),
  scoresJson: __t.string(),
  checksJson: __t.string(),
  notesJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type SceneReviewProjection = __Infer<typeof SceneReviewProjection>;

export const StreamBranchProjection = __t.object("StreamBranchProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  streamId: __t.string(),
  parentStreamId: __t.string(),
  forkAt: __t.u32(),
  createdAtMs: __t.u64(),
});
export type StreamBranchProjection = __Infer<typeof StreamBranchProjection>;

export const StreamReceipt = __t.object("StreamReceipt", {
  id: __t.string(),
  workspaceId: __t.string(),
  streamId: __t.string(),
  seq: __t.u64(),
  receiptId: __t.string(),
  occurredAtMs: __t.u64(),
  prevHash: __t.string(),
  hash: __t.string(),
  bodyJson: __t.string(),
  hintsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type StreamReceipt = __Infer<typeof StreamReceipt>;

export const StreamReceiptProjection = __t.object("StreamReceiptProjection", {
  id: __t.string(),
  workspaceId: __t.string(),
  streamId: __t.string(),
  seq: __t.u64(),
  receiptId: __t.string(),
  occurredAtMs: __t.u64(),
  prevHash: __t.string(),
  hash: __t.string(),
  bodyJson: __t.string(),
  hintsJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type StreamReceiptProjection = __Infer<typeof StreamReceiptProjection>;

export const ViewerCapability = __t.object("ViewerCapability", {
  capabilityHash: __t.string(),
  capabilityId: __t.string(),
  runId: __t.string(),
  maxUses: __t.u32(),
  uses: __t.u32(),
  ttlSeconds: __t.u32(),
  expiresAt: __t.option(__t.timestamp()),
  revoked: __t.bool(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ViewerCapability = __Infer<typeof ViewerCapability>;

export const ViewerCapabilityExpiration = __t.object("ViewerCapabilityExpiration", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  capabilityId: __t.string(),
  expiresAtMicros: __t.u64(),
});
export type ViewerCapabilityExpiration = __Infer<typeof ViewerCapabilityExpiration>;

export const ViewerCapabilityRunMember = __t.object("ViewerCapabilityRunMember", {
  id: __t.string(),
  runId: __t.string(),
  member: __t.identity(),
  createdAt: __t.timestamp(),
});
export type ViewerCapabilityRunMember = __Infer<typeof ViewerCapabilityRunMember>;

export const ViewerRedemption = __t.object("ViewerRedemption", {
  id: __t.string(),
  capabilityId: __t.string(),
  runId: __t.string(),
  member: __t.identity(),
  createdAt: __t.timestamp(),
});
export type ViewerRedemption = __Infer<typeof ViewerRedemption>;

export const WorkerCapabilityProjection = __t.object("WorkerCapabilityProjection", {
  id: __t.string(),
  runId: __t.string(),
  capability: __t.string(),
  createdAt: __t.timestamp(),
});
export type WorkerCapabilityProjection = __Infer<typeof WorkerCapabilityProjection>;

export const WorkspaceProjection = __t.object("WorkspaceProjection", {
  id: __t.string(),
  name: __t.string(),
  role: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type WorkspaceProjection = __Infer<typeof WorkspaceProjection>;

export const WorkspaceUsageProjection = __t.object("WorkspaceUsageProjection", {
  workspaceId: __t.string(),
  jobsInWindow: __t.u32(),
  activeJobs: __t.u32(),
  totalJobs: __t.u64(),
  maxJobsInWindow: __t.u32(),
  maxActiveJobs: __t.u32(),
  windowStartedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type WorkspaceUsageProjection = __Infer<typeof WorkspaceUsageProjection>;

export const WorkspaceViewerCapability = __t.object("WorkspaceViewerCapability", {
  capabilityHash: __t.string(),
  capabilityId: __t.string(),
  workspaceId: __t.string(),
  maxUses: __t.u32(),
  uses: __t.u32(),
  expiresAt: __t.timestamp(),
  revoked: __t.bool(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type WorkspaceViewerCapability = __Infer<typeof WorkspaceViewerCapability>;

export const WorkspaceViewerRedemption = __t.object("WorkspaceViewerRedemption", {
  id: __t.string(),
  capabilityId: __t.string(),
  workspaceId: __t.string(),
  member: __t.identity(),
  createdAt: __t.timestamp(),
});
export type WorkspaceViewerRedemption = __Infer<typeof WorkspaceViewerRedemption>;
